### ISSUE TITLE
`ctrl+d` does not work

### ISSUE THREAD

**Issue by NikosEfthias** [VSCodeVim/Vim#1009]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.
---
### What did you do?

`ctrl+d` to insert multiple cursors
Put the exact keys you pressed.
`ctrl+d`
### What did you expect to happen?

match and edit multiple locations
### What happened instead?

Just matched but edited the first position only
### Technical details:
- VSCode Version:1.6x
- VsCodeVim Version: .4
- OS: ubuntu 16.4

**Comment by rreusser** [comment]
@NikosEfthias See [Supported Options](https://github.com/VSCodeVim/Vim#supported-options) in order t  enable this feature. I just had to add `"vim.useCtrlKeys": true` to my settings.json (that section of the README describes how to do this).

Hopefully that solves it. My only issue then would be whether `useCtrlKeys: false` is a friendly default since the fact that my primary motion command appeared unimplemented was almost enough to turn me off from vscode entirely under the assumption that vim support just wasn't very functional yet. (Which is obviously wrong. Thanks sooo much for this extension!)

**Comment by NikosEfthias** [comment]
@rreusser what I meant is that the `ctrl+d` combination of vscode is blocked by vim not otherwise

**Comment by rreusser** [comment]
Ohh, sorry, my mistake! I read it too hastily and assumed you meant ctrl+d for *vim* was not enabled by default. I understand now. Please disregard!

**Comment by johnfn** [comment]
You should use `gc` instead, which is a new command we added to work like `ctrl-d` (since ctrl-d is already something else).

Weird question for @rebornix etc. In the case where useCtrlKeys is off, should we continue to override ctrl-d but make it do what `gc` does instead? :P

**Comment by rebornix** [comment]
@johnfn I'm not quite sure how many users are leveraging ctrl-d to do what they want. It's a common problem that ppl may just want to disable one single Vim command and use Code's builtin command instead. We have a general discussion about multiple keymaps and will let you know if we have any update on this.

**Comment by NikosEfthias** [comment]
well `gc` solved the issue pretty much actually @rebornix i think we can set the issue closed

**Comment by krasnovpro** [comment]
You mean [`gb`](https://github.com/VSCodeVim/Vim#vscodevim-tricks)?
