### ISSUE TITLE
Can Visual Studio Code use Vim Plugins?

### ISSUE THREAD

**Issue by nikitavoloboev** [VSCodeVim/Vim#1025]
OS : macOS

**Comment by Phrohdoh** [comment]
No.

VimL would have to be transpiled to TS and even that wouldn't be enough.
(Vim's APIs are nothing like vscode's)

**Comment by nikitavoloboev** [comment]
I understand. Thank you.

Just one quick question, don't want to make new issue out of it.

Is it possible to set a leader key space in vs code vim?

**Comment by johnfn** [comment]
The official answer here is that although we will never be able to natively support Vim plugins because we don't parse VimL, we are 100% open to PRs that reimplement these plugins into TypeScript. EasyMotion by @Metamist is a great example of this: #993

I don't fully understand your question about the leader, but feel free to ask us on slack: https://vscodevim-slackin.azurewebsites.net/
