### ISSUE TITLE
Use `line` as `editor.cursorstyle` in insert mode does not work anymore

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#1036]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I used `line` as `editor.cursorstyle` setting.

### What did you expect to happen?

I expect that in insert mode the cursor is line style.

### What happened instead?

Instead it is block style.

I tried to set it in my settingsfile back to `line`, but had to discover that it is overwritten by the vim plugin. 
![cursorstyle](https://cloud.githubusercontent.com/assets/3358663/19996354/356c23ba-a25f-11e6-838b-1e8193efb278.gif)
I think that function is doing that https://github.com/VSCodeVim/Vim/blob/792551c8574e4e8012235c3ee741b1a36a9b715e/src/configuration/configuration.ts#L85, but i don't know if it is intentional or a issue?

### Technical details:

* VSCode Version: 1.7.0-insider
* VsCodeVim Version: master on 792551c8574e4e8012235c3ee741b1a36a9b715e
* OS: Win7

**Comment by rebornix** [comment]
Okay I see it. As Vim takes over the configuration stuff, we are persisting the cursor style into the config file instead of caching it in each editor. @johnfn do you think for this particular we should avoid doing so?

**Comment by Platzer** [comment]
Is it possible that vim also overwrite settings like `tabsize`, because my settings file is currently a bit strange?

**Comment by rebornix** [comment]
It would be easy enough to put `tabstop` in contribution section of `package.json` and then our internal configuration module will take that. @Platzer wants to give it a try? I didn't do that in the beginning as at that time we could sync this setting between Code and Vim but now we are good to go.

**Comment by Platzer** [comment]
@rebornix i think we're talking from diffrent things here. I think vscode\vim overwrite my current `editor.insertSpaces` settings because i always had it set to `true`. And see above gif somehow it changed to `false`? I'm not sure because i cannot reproduce it.

I'm don't understand why it is necessary to sync the overlapping settings? Why not just use the vscode settings instead?

**Comment by rebornix** [comment]
I thought you were asking if that's possible. Please note first vscodevim doesn't override `editor.insertSpaces`, like I mentioned above I didn't implement this part yet.

For overlapping part, users might just want to use `.vimrc` as configuration (which is not implemented yet) or use ex command `set tabsize=4` to change the configure temporarily.

**Comment by Platzer** [comment]
`editor.insertSpaces` is already impelemented: https://github.com/VSCodeVim/Vim/blob/792551c8574e4e8012235c3ee741b1a36a9b715e/src/configuration/configuration.ts#L70.

And that line https://github.com/VSCodeVim/Vim/blob/792551c8574e4e8012235c3ee741b1a36a9b715e/src/configuration/configuration.ts#L118 writes it to the `settings.json` (see: http://code.visualstudio.com/docs/extensionAPI/vscode-api#WorkspaceConfiguration).

I just had to know if we're on the same page. All overlapping settings should not be persisted? They should only overrule the settings temporarily?

**Comment by rebornix** [comment]
If I remember the implementation correctly, https://github.com/VSCodeVim/Vim/blob/792551c8574e4e8012235c3ee741b1a36a9b715e/src/configuration/configuration.ts#L108 is used to avoid first time assignment. So if you don't put `insertSpaces` in your configure file, we won't trigger any update to Code's configuration. Since we don't put it in the `package.json`, Code won't provide a default value for `insertSpaces`, so https://github.com/VSCodeVim/Vim/blob/792551c8574e4e8012235c3ee741b1a36a9b715e/src/configuration/configuration.ts#L38 is safe. It means, if you don't add `insertSpaces` into your configure file or run `:set insertSpaces`, no one will finally make changes to Code's config.

Above is just my design principle when I wrote the code, so correct me if the implementation is no longer this way.

Besides, about overlapping settings, you are right, not all of them should be persisted. I mentioned this already https://github.com/VSCodeVim/Vim/issues/1036#issuecomment-259487726 :)
