### ISSUE TITLE
Configure highlight colour

### ISSUE THREAD

**Issue by OliverJAsh** [VSCodeVim/Vim#1052]
I have `vim.hlsearch` set, and would like to change the colour of highlighted search matches to match VSCode's default

Vim search

![image](https://cloud.githubusercontent.com/assets/921609/20215148/68cc851e-a80a-11e6-85e1-d420a05be5cb.png)

VSCode search

![image](https://cloud.githubusercontent.com/assets/921609/20215165/7b8cddd4-a80a-11e6-98ae-5885aa05e2ba.png)

**Comment by johnfn** [comment]
That makes a lot of sense.

**Comment by johnfn** [comment]
Added a configuration setting on master. Will land in 0.4.7!

**Comment by dsifford** [comment]
@johnfn Is it possible to do a lookup for the user's active theme settings?

If so, this would be ideal because you could just set the default value(s) as the value of `findMatchHighlight` and `currentFindMatchHighlight`. That way, it'll match the colors that result when the user does a `ctrl-f` search.

(Again, not even sure this is possible, but I figured I'd toss the idea out there just in case).

Thanks for your work on this project! 😄

**Comment by xconverge** [comment]
@dsifford I do not think the vscode API has current theme info unfortunately... @rebornix correct me if I am wrong?
