### ISSUE TITLE
When disable or uninstall, Cursor remains wide-width.

### ISSUE THREAD

**Issue by Darkttd** [VSCodeVim/Vim#1092]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Install vim extension.
next, disable or uninstall it,
the cursor remains wide width.
![image](https://cloud.githubusercontent.com/assets/6015765/20624706/ccee499a-b351-11e6-83a6-b8a5ad9475e7.png)

### What did you expect to happen?
the cursor come back to original width.

### What happened instead?
the cursor remains wide width.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.3
* OS: Windows 10 Home

**Comment by johnfn** [comment]
@Darkttd, you can fix this problem by going into your user profile settings and finding the setting for block cursor and removing it. It looks like this:

`    "editor.cursorStyle": "block"`

@rebornix This happens because of our "save settings directly to user settings file always" feature. I'm not sure what the proper way to fix it is, though. You can't just remove all vim-related settings, because what if a _different_ extension also put that setting in there? This strikes me as a poor decision by VSCode...

**Comment by Darkttd** [comment]
@johnfn Thank you. the cursor come back original width :)
