### ISSUE TITLE
gt/T doesn't take editor groups in account

### ISSUE THREAD

**Issue by asvetliakov** [VSCodeVim/Vim#1131]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
* Open 2 files in left editor and 2 files in the right editor groups
* ```gt``` in the left/right editor group 

### What did you expect to happen?
```gt``` (and similar commands) switches editors only in one group

### What happened instead?
```gt``` cycles in all editor groups

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: *0.4.9*
* OS: macOS Sierra

**Comment by johnfn** [comment]
I don't understand what you mean by "cycles in all editor groups". Could you explain in more detail please?

**Comment by asvetliakov** [comment]
Oh i'm sorry, i mean ```gt```

**Comment by mixedCase** [comment]
@johnfn He probably means that gt/gT navigates tabs throughout editor splits (if more than one is open) instead of keeping to the current split. What behavior is correct is ambiguous, since as we all know Vim tabs are pretty different from VSCode tabs; but I believe having it scroll through the currently focused split would be more useful than the current behavior.

For what it's worth, navigating only within the split only is what IdeaVim (IntelliJ plugin) does, and coming from there I sorely miss it.

**Comment by Chillee** [comment]
PR https://github.com/VSCodeVim/Vim/pull/1677 actually fixed this issue.
