### ISSUE TITLE
Simple Delete Word Does Not Work In Macros

### ISSUE THREAD

**Issue by maxponte** [VSCodeVim/Vim#1157]
### What did you do?

qqfTdW0jq@q

### What did you expect to happen?

Begin recording "q" macro, find the next "T", delete word, go to beginning of line, go to next line, end macro, play macro on the new line

### What happened instead?

When I attempted to play the macro, delete word does not work

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: MacOS 10.11.6

**Comment by z2oh** [comment]
It should be noted that the delete command by itself is not the root cause of this issue. qqdwq@q will delete word, for example. It seems to occur specifically when a delete command is issued after a search command. qqt"dwq@q for example will jump to the first instance of " but then not delete anything. Furthermore, the macro appears to then halt entirely. so qqt"dwjq@q will move the cursor to the first " as expected, but then not delete anything and not move the cursor to the line below.

This is probably the same issue as #1091.

**Comment by xconverge** [comment]
This is all good now!
