### ISSUE TITLE
feature request: move search input from status bar to command bar

### ISSUE THREAD

**Issue by Jimmy-Z** [VSCodeVim/Vim#1206]
when using / or ? to start a search, it shows in status bar at the bottom of the screen.
when using : to start a command, it shows in a dedicated command bar at the top of the screen.

please choose a unified location, preferably a command bar at the bottom of the screen.
* conforms to original vim
* status bar is not available in zen mode

this is a minor issue but really annoying to me, lots of time I start a search/command and stare at wrong place of the screen.

**Comment by johnfn** [comment]
I would love to have everything in the panel at the top of the screen. However, VSCode hasn't provided us with quite enough functionality to do e.g. search on the top of the screen. (we can't register a down arrow and then do search history, for instance.) So we use the status bar, which I consider to be suboptimal mostly because it's so darn small, when we can't use the top panel.

**Comment by rebornix** [comment]
The reason that I used pop up window for ex commands as that's more interactive. However for search, I agree with @johnfn current implementation is the most reasonable way at this moment.

**Comment by jpoon** [comment]
Fixed with https://github.com/VSCodeVim/Vim/pull/2758
