### ISSUE TITLE
`/` search scrolls to the top of the file even when results are found on same screen

### ISSUE THREAD

**Issue by prog666** [VSCodeVim/Vim#1422]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

/this

### What did you expect to happen?

to find all occurrences of 'this' on same screen

### What happened instead?

it starts search from beginning of the file

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: macOS sierra

**Comment by johnfn** [comment]
It's actually really hard to reproduce this, because it doesn't happen with most words or searches. Could you possibly narrow down what is triggering the bad behavior?

Thanks!

**Comment by prog666** [comment]
Leave cursor at first line, scroll down, search.

**Comment by johnfn** [comment]
Err, that behavior makes sense to me, because incremental search always starts at the position of the cursor. 

The behavior is a bit different from Vim because in Vim the cursor moves to always stay within the viewport when you scroll. We decided not to use that behavior because it feels kinda weird in an IDE.

**Comment by prog666** [comment]
but maybe it's a good idea to make an option to choose if you want to keep cursor in the viewport?

**Comment by johnfn** [comment]
That issue is over here - feel free to thumbs it up: https://github.com/VSCodeVim/Vim/issues/873 :)
