### ISSUE TITLE
Please sync rollouts and github releases

### ISSUE THREAD

**Issue by jeffschwartz** [VSCodeVim/Vim#1483]
I just installed 0.6.15 but when I pull up releases on Github I see the following:
![screen shot 2017-04-07 at 9 50 33 am](https://cloud.githubusercontent.com/assets/271288/24802980/c31d095e-1b77-11e7-9d97-871aa4ecf408.png)

I expect to see the release matching the one I am installing but as you can see they differ.

This has been the case for a while now and it makes it difficult if not impossible to know anything about the scope of changes in the version I installed. So please post the release to Github prior to pushing the update out for consumption.

In addition, I think it would be really great if there was an actual change log :)

BTW, VSCodeVim is fantastic and thank you to all the contributors involved.

**Comment by johnfn** [comment]
The release notes ARE the changelog. Hence why they link to the release notes. :wink:

Updating the changelog is a boring and manual process, which often competes with going to bed for our attention. :) Which is why we sometimes skimp. To be fair, most of the time when we do skip out on the changelog, it's just a very trivial bug fix, as it was in this version. 

I'm going to close this issue, but the request for a clearer and more up to date changelog has been heard. Thanks!

**Comment by xconverge** [comment]
I just generated this changelog with https://github.com/skywinder/github-changelog-generator

Thoughts? I think it actually looks pretty good for something auto generated...




# Change Log

## [Unreleased](https://github.com/VSCodeVim/Vim/tree/HEAD)

[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.13...HEAD)

**Closed issues:**

- Please sync rollouts and github releases [\#1483](https://github.com/VSCodeVim/Vim/issues/1483)
- Auto indent in matching brace not working in scss files [\#1482](https://github.com/VSCodeVim/Vim/issues/1482)
- Pressing 'x' multiple times freezes interface [\#1480](https://github.com/VSCodeVim/Vim/issues/1480)
- add selection to next find match \(CMD+D\) broken on macOS [\#1478](https://github.com/VSCodeVim/Vim/issues/1478)
- The multi-cursor shortcut 'gc' won't work [\#1477](https://github.com/VSCodeVim/Vim/issues/1477)
- z. command  \(redraw, current line at center of window\) does not work [\#1475](https://github.com/VSCodeVim/Vim/issues/1475)
- Latest update changed insert cursor [\#1473](https://github.com/VSCodeVim/Vim/issues/1473)
- Insert mode cursor is now the block instead of the pipe [\#1470](https://github.com/VSCodeVim/Vim/issues/1470)
- Holding down . completely crashes VSCodeVim [\#1463](https://github.com/VSCodeVim/Vim/issues/1463)
- Toggle zen mode conflicts with vim commands [\#1457](https://github.com/VSCodeVim/Vim/issues/1457)
- EasyMotion up/down \(j/k\) [\#1448](https://github.com/VSCodeVim/Vim/issues/1448)

**Merged pull requests:**

- fixes \#1475 [\#1485](https://github.com/VSCodeVim/Vim/pull/1485) ([xconverge](https://github.com/xconverge))
- fix for double clicking a word with mouse not showing selection properly [\#1484](https://github.com/VSCodeVim/Vim/pull/1484) ([xconverge](https://github.com/xconverge))
- fix easymotion j and k [\#1474](https://github.com/VSCodeVim/Vim/pull/1474) ([xconverge](https://github.com/xconverge))
- Fix tables in roadmap [\#1469](https://github.com/VSCodeVim/Vim/pull/1469) ([xconverge](https://github.com/xconverge))
- Fix visual block mode not updating multicursor selection [\#1468](https://github.com/VSCodeVim/Vim/pull/1468) ([xconverge](https://github.com/xconverge))
- Fix type suggestion for handleKeys object [\#1465](https://github.com/VSCodeVim/Vim/pull/1465) ([abhiranjankumar00](https://github.com/abhiranjankumar00))

## [v0.6.13](https://github.com/VSCodeVim/Vim/tree/v0.6.13) (2017-04-04)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/0.6.12...v0.6.13)

**Merged pull requests:**

- fixes \#1448 [\#1462](https://github.com/VSCodeVim/Vim/pull/1462) ([xconverge](https://github.com/xconverge))

## [0.6.12](https://github.com/VSCodeVim/Vim/tree/0.6.12) (2017-04-04)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.11...0.6.12)

**Implemented enhancements:**

- Ability to add multiple cursors with alt + mouseclick like native VSCode [\#887](https://github.com/VSCodeVim/Vim/issues/887)

**Fixed bugs:**

- Multi-Cursor Strange insert after deleting with Ctrl-Backspace [\#1224](https://github.com/VSCodeVim/Vim/issues/1224)
- underline cursorstyle have no effect [\#1158](https://github.com/VSCodeVim/Vim/issues/1158)
- Can't add cursor above or below for multi-cursor when created with task [\#860](https://github.com/VSCodeVim/Vim/issues/860)

**Closed issues:**

- Clicking on the active tab reverts the cursor to an i beam [\#1460](https://github.com/VSCodeVim/Vim/issues/1460)
- `ci"`, `dsb` are not repeatable with `.` [\#1456](https://github.com/VSCodeVim/Vim/issues/1456)
- g-d and g-D doesn't work. [\#1447](https://github.com/VSCodeVim/Vim/issues/1447)
- Undo/redo broke between 0.6.5 and 0.6.11 [\#1445](https://github.com/VSCodeVim/Vim/issues/1445)
- : with visual region selected should not highlight command line text [\#1444](https://github.com/VSCodeVim/Vim/issues/1444)
- `command + c` then `command + v` lead to messy words [\#1440](https://github.com/VSCodeVim/Vim/issues/1440)
- Ctrl+c in insert mode does not copy text, and unexpectedly switches to normal mode [\#1437](https://github.com/VSCodeVim/Vim/issues/1437)
- Incorrect behavior when editing with multiple cursors [\#1432](https://github.com/VSCodeVim/Vim/issues/1432)
- Inner tag "it" not working when tag has other tags in it [\#1430](https://github.com/VSCodeVim/Vim/issues/1430)
- Allow users to delegate certain keys back to vscode [\#1424](https://github.com/VSCodeVim/Vim/issues/1424)
- gUU and guu doesn't work [\#1423](https://github.com/VSCodeVim/Vim/issues/1423)
- `/` search scrolls to the top of the file even when results are found on same screen [\#1422](https://github.com/VSCodeVim/Vim/issues/1422)
- `gj` and `gk` visual lines movement operations don't preserve column place. [\#1419](https://github.com/VSCodeVim/Vim/issues/1419)
- c\[change\] d\[elete\] with f" don't work [\#1417](https://github.com/VSCodeVim/Vim/issues/1417)
- How does format work in vim plugin? [\#1415](https://github.com/VSCodeVim/Vim/issues/1415)
- How can i create custom keybindings? [\#1409](https://github.com/VSCodeVim/Vim/issues/1409)
- Count commands do not honor `otherModesKeyBindingsNonRecursive` settings [\#1378](https://github.com/VSCodeVim/Vim/issues/1378)
- Not respecting the cusor-style value [\#1356](https://github.com/VSCodeVim/Vim/issues/1356)
- This extension completely breaks the `Select All Occurrences` command [\#1312](https://github.com/VSCodeVim/Vim/issues/1312)
- Make easymotion use `searchHighlightColor` for motion placer [\#1245](https://github.com/VSCodeVim/Vim/issues/1245)
- Changing cursor position with arrows or mouse in insert does not create an undo point [\#1168](https://github.com/VSCodeVim/Vim/issues/1168)
- Simple Delete Word Does Not Work In Macros [\#1157](https://github.com/VSCodeVim/Vim/issues/1157)

**Merged pull requests:**

- fixes \#1432 [\#1434](https://github.com/VSCodeVim/Vim/pull/1434) ([xconverge](https://github.com/xconverge))
- fixes \#1312 [\#1433](https://github.com/VSCodeVim/Vim/pull/1433) ([xconverge](https://github.com/xconverge))
- Change easymotion decoration colors to use searchHighlight colors [\#1431](https://github.com/VSCodeVim/Vim/pull/1431) ([xconverge](https://github.com/xconverge))
- minor cleanup to improve leader usage with \<space\> [\#1429](https://github.com/VSCodeVim/Vim/pull/1429) ([xconverge](https://github.com/xconverge))
- gUU and guu [\#1428](https://github.com/VSCodeVim/Vim/pull/1428) ([xconverge](https://github.com/xconverge))
- Allowing user to selectively disable some key combos [\#1425](https://github.com/VSCodeVim/Vim/pull/1425) ([xconverge](https://github.com/xconverge))
- Remapper cleanup key history [\#1416](https://github.com/VSCodeVim/Vim/pull/1416) ([xconverge](https://github.com/xconverge))
- fix undo points when moving around in insert with mouse or arrow keys [\#1413](https://github.com/VSCodeVim/Vim/pull/1413) ([xconverge](https://github.com/xconverge))
- update readme for plugins [\#1411](https://github.com/VSCodeVim/Vim/pull/1411) ([xconverge](https://github.com/xconverge))
- Allow users to use their own cursor style for insert from editor.cursorStyle [\#1399](https://github.com/VSCodeVim/Vim/pull/1399) ([xconverge](https://github.com/xconverge))

## [v0.6.11](https://github.com/VSCodeVim/Vim/tree/v0.6.11) (2017-03-19)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.10...v0.6.11)

**Implemented enhancements:**

- Performance is slow [\#897](https://github.com/VSCodeVim/Vim/issues/897)

**Closed issues:**

- Keybindings not working in 10.0.2 [\#1410](https://github.com/VSCodeVim/Vim/issues/1410)
- Motion keys {h,j,k,l} don't move more than one position upon holding down [\#1407](https://github.com/VSCodeVim/Vim/issues/1407)
- Three letter keybindings fail to match on version 0.6.6 [\#1405](https://github.com/VSCodeVim/Vim/issues/1405)
- ZZ example on the main page does not save in 1.10.2 [\#1397](https://github.com/VSCodeVim/Vim/issues/1397)

**Merged pull requests:**

- Fix comment syntax for shell commands. [\#1408](https://github.com/VSCodeVim/Vim/pull/1408) ([frewsxcv](https://github.com/frewsxcv))
- Increase timeout for some test cases in mocha [\#1379](https://github.com/VSCodeVim/Vim/pull/1379) ([xconverge](https://github.com/xconverge))

## [v0.6.10](https://github.com/VSCodeVim/Vim/tree/v0.6.10) (2017-03-18)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.9...v0.6.10)

**Closed issues:**

- Feature request: Support Ctrl+O Ctrl+I in command mode to navigate cursor locations [\#1253](https://github.com/VSCodeVim/Vim/issues/1253)

## [v0.6.9](https://github.com/VSCodeVim/Vim/tree/v0.6.9) (2017-03-18)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.8...v0.6.9)

## [v0.6.8](https://github.com/VSCodeVim/Vim/tree/v0.6.8) (2017-03-18)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.7...v0.6.8)

## [v0.6.7](https://github.com/VSCodeVim/Vim/tree/v0.6.7) (2017-03-18)
[Full Changelog](https://github.com/VSCodeVim/Vim/compare/v0.6.6...v0.6.7)

**Closed issues:**

- Changing the open tab changes cursor to non-block [\#1404](https://github.com/VSCodeVim/Vim/issues/1404)

**Merged pull requests:**

- fix bracket motion behavior for use with % and a count, or \[\( and a c… [\#1406](https://github.com/VSCodeVim/Vim/pull/1406) ([xconverge](https://github.com/xconverge))
- fix for cursor not changing correctly, workaround for vscode issue [\#1402](https://github.com/VSCodeVim/Vim/pull/1402) ([xconverge](https://github.com/xconverge))

**Comment by jeffschwartz** [comment]
Thanks @johnfn for the speedy reply. What release notes are you referring to if you don't mind me asking? My concern -- I probably could have been clearer :) - is that when VS Code informs me that there is an update more often than not there isn't a tagged version for the release and going to the release tab on github shows that the latest release is older than the one VS Code is showing me for updating. I hope that clarifies my intention if I failed to do so initially. 

I will frequently pass on plugin updates if there isn't any or enough information provided as to what they contain. Maintaining a stable environment for development, as I am sure you would understand, is very important to me and I would guess to others as well. A change log most definitely would suffice to provide that information but in lieu of that a tagged version with comments on the github releases tab will also do.

Thanks again to all the dedicated maintainers of this awesome Vim plugin for VS Code.

**Comment by jeffschwartz** [comment]
Here @johnfn is a current example of what concerns me. Below is a screen shot of the Changelog tab in VSCode plugin manager for the plugin. Notice that the version installed is currently 0.6.15:

![screen shot 2017-04-08 at 2 20 37 pm](https://cloud.githubusercontent.com/assets/271288/24831386/99b4e3b2-1c66-11e7-897b-e622643237ac.png)

When I click on the "Please click here for our changelog" link it takes me to the release tab of the plugins repo and currently the latest release posted is 0.6.13 which is older than the one I have installed:

![screen shot 2017-04-08 at 2 23 26 pm](https://cloud.githubusercontent.com/assets/271288/24831411/f7e8a2d4-1c66-11e7-9a85-d58c1fe5ed9e.png)

So without a changelog and no tagged version for the update where then can I find the details of the update?

**Comment by xconverge** [comment]
@jeffschwartz yea understood, in all honesty, this usually happens when there is a bad bug that the tests did not catch. We do an ideal release with some decent notes, then within a day or so, if a bunch of users report something critical that regressed and the tests did not catch, there may be 1 or 2 hotfix releases to fix the critical issue. We could easily just add a line saying "fixed this critical issue, hotfix release", but are usually more focused on getting it released to maintain the status quo of peoples development.

We also add the .vsix extension to the releases, so that if you happen to update and something is completely broken for YOU, you can install the version you were using before and ignore updates for a few days or weeks until you trust us again :)

It is easy to solve, improve the release notes :)

**Comment by xconverge** [comment]
I just generated this changelog with https://github.com/skywinder/github-changelog-generator

Thoughts? I think it actually looks pretty good for something auto generated...

Here was my autogenerated changelog:

https://markdownshare.com/view/8b238cf5-2f01-47c0-bc9f-2bb190d4cb61

I pasted it into this issue at first and now it referenced every single issue to this issue, oops..

**Comment by johnfn** [comment]
Yeah I mean if you guys are okay with autogenerated release notes, then maybe I have been overthinking things. I didn't want to do that because I didn't think you'd be able to read them well, but hey, if they're actually okay...
