### ISSUE TITLE
EasyMotion handles are cropped

### ISSUE THREAD

**Issue by icewind** [VSCodeVim/Vim#1501]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

< leader >< leader >sg

### What did you expect to happen?

Easymotion handle should appear fullsize(at least readable)

### What happened instead?

Easymotion handle appears cropped and unreadable https://yadi.sk/i/huvSgYBF3Gu4Kf

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: Mac OS 10.11.3

**Comment by xconverge** [comment]
This has all been fixed on master and the handles are completely customizable in master. Thanks and keep your eye out for the next release

**Comment by joeynguyen** [comment]
@xconverge Has this been released yet?  There have been a few releases since this issue got closed but I'm still seeing the shortcuts keys get cropped - https://drive.google.com/file/d/0B7J6itD1udPrbURESTh0S29qQ3M/view

Notice how the 'g' in 'ng' gets cropped at the bottom and how other letters get cropped as well.

These are my settings:
    "vim.easymotionMarkerHeight": 14,
    "vim.easymotionMarkerWidthPerChar": 8,
    "vim.easymotionMarkerYOffset": 14,

I've played around with adjusting them but this is the best I can get it to look.  If I make Y offset lower, you can see the bottom of the 'g' but all the shortcut characters are moved up from the rest of the text which I think looks weird.
