### ISSUE TITLE
vim.autoindent should indent according surrounding lines (block), not according current line

### ISSUE THREAD

**Issue by fgarcia** [VSCodeVim/Vim#1502]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Created a new line and played around with the setting `vim.autoindent` 

### What did you expect to happen?

I want new lines to be indented according the block indentation

### What happened instead?

New line was indented according line position

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: Mac OS 10.12.4

### Screenshots

![captura de ecra 2017-04-12 as 15 43 16](https://cloud.githubusercontent.com/assets/253157/24961022/ceba3b50-1f97-11e7-85e4-d1dcc8f05bf8.png)

![captura de ecra 2017-04-12 as 15 50 39](https://cloud.githubusercontent.com/assets/253157/24961040/dbbd8de8-1f97-11e7-886c-80cd1cc7fc06.png)

**Comment by Chillee** [comment]
What do you mean by "created a new line"?

**Comment by fgarcia** [comment]
In the first picture my cursor is at column 0. I "press letter 'o'" to create a new line. In Vim this would start a new line with a cursor at the indentation level.

The "new text" in the second picture is not pasted, is what I wrote after pressing 'o'

**Comment by diminutivesloop** [comment]
I'm not quite sure what this issue is getting at, but I'd be satisfied if `vim.autoindent` simply matched the behavior of `editor.autoindent`.

**Comment by lubaroli** [comment]
In the current version (1.47.2) this seems to work correctly for positioning the cursor and adding new text. However, when adding a new line above/below the current cursor and pasting, indentation is not followed and the pasted input is placed at column 0.

**Comment by berknam** [comment]
> 
> 
> In the current version (1.47.2) this seems to work correctly for positioning the cursor and adding new text. However, when adding a new line above/below the current cursor and pasting, indentation is not followed and the pasted input is placed at column 0.

What do you mean by:
> adding a new line above/below the current cursor and pasting

If you are doing this by pressing or using a remap to `o<Esc>p` then whats happening is:
- After `o` it creates a new line with indentation and enters insert mode
- After `<Esc>` it goes to normal mode and removes the indentation (the cursor goes to column 0)
- After `p` it pastes on column 0 (without indentation)

This is normal Vim behavior. Also if you yank linewise and then paste it will not change the original indentation of the yanked text.

What you want to do in order to paste some text and keep indentation is pressing `o` or `O` to create a new line below or above and enter insert mode, then press `<C-r>` to insert from register and then choose the register you want like `"` for the unnamed register or `+` for the system clipboard, or some other register you yanked to.

**Comment by lubaroli** [comment]
Thanks for the reply and sorry for the unclear comment. Yes, the use case I meant is exactly what you described.

Furthermore, using `<C-r>` without leaving insert mode does work. Also, when using linewise copy/paste, the indentation level of the original line is kept.

I understand this is the expected Vim behaviour, but having recently migrated from PyCharm, I'd also expect the editor to handle the auto-indent contextually on both of the cases above. However, since this is in accordance to Vim behaviour, I agree this comment is most likely referring to VS Code editor per se and not the Vim extension.

**Comment by J-Fields** [comment]
@lubaroli `]p` is probably worth mentioning, though it isn't exactly what you're requesting:

```
["x]]p		    or					*]p* *]<MiddleMouse>*
["x]]<MiddleMouse>	Like "p", but adjust the indent to the current line.
			Using the mouse only works when 'mouse' contains 'n'
			or 'a'.
```

#1269 would be a more complete solution, but isn't currently implemented.

**Comment by berknam** [comment]
I think this issue could be closed now, since the issue initially stated has since been fixed. Or is there still any other problem related to this?

**Comment by lubaroli** [comment]
> #1269 would be a more complete solution, but isn't currently implemented.

Thanks @J-Fields, looking forward to see that one implemented.

> I think this issue could be closed now, since the issue initially stated has since been fixed. Or is there still any other problem related to this?

I think so too.
