### ISSUE TITLE
Repeated `s` behaves incorrectly

### ISSUE THREAD

**Issue by rnewman** [VSCodeVim/Vim#1519]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

`0iHello<Esc>04sfoo<Esc>`

### What did you expect to happen?

`Hello` is typed. Cursor moves back to column zero.

The first four characters are replaced by `foo`, leaving `fooo`. This is what Vim does.

### What happened instead?

The first four characters are replaced by `foo` _four times_, leaving `foofoofoofooo`.

### Technical details:

* VSCode Version:

1.12.0-insider

* VsCodeVim Version: *[please ensure you are on the latest]*

0.6.16.

* OS: 

Mac 10.12.4.

**Comment by xconverge** [comment]
Ah good catch! I should be able to fix this ASAP, I know exactly where I did this...

**Comment by johnfn** [comment]
@rnewman just to clarify, by clicking on the confused face you're indicating that not being able to repeat `s` is so bad that you can't use VSCodeVim?

**Comment by rnewman** [comment]
@johnfn:

Perhaps we have different definitions of 'unusable' — clearly I'm still able to use VSCode and VSCodeVim — I simply perceived some hyperbole in the wording of the instructions. I read the instructions as 👍 = "please address" (vote), 😕 = "primary interaction bug, not an enhancement request" (boolean category). As such I set both flags.

I do this kind of `s`-repeat about twenty times a day, so I'm having to stumblingly stop myself and engage grey matter to rephrase what I'm trying to do to avoid blatting repeats into my code. In a Vim-like it's pretty bad to have a command sequence produce incorrect results.

This is not a bug that causes the plugin to fail to load, to corrupt files, or wipe my disk. (If it were, I would have noted it in the issue title.)

But if there were a competing Vim-alike for VSCode with approximate feature parity that didn't have this bug, I'd switch to it.

Does that clarify?

**Comment by johnfn** [comment]
So the reason I was asking is, the idea of 😕  was to be a sort of super 👍  - to indicate "holy smokes this is so bad that I gave up on VSCodeVim and went back to whatever I was using before" - I wanted to get a signal for something that expressed more "argh" than a simple thumbs up would. And so I wanted to see if people were understanding it in the same way that I intended.

You do seem to be using it as a super 👍 , so that's good (well, it's not good that it's broken!). It's not exactly tapping into the "I had to leave vscode" that I thought it would, but maybe that's okay?

**Comment by rnewman** [comment]
Perhaps I just find VSCodeVim sufficiently invaluable that it's hard to imagine not using it? 😄 

I do think it's worth trying to find a mechanism for users to differentiate between feature requests and serious bugs, particularly without 'me too' comments. It'd be nice if GitHub had more reaction options…

**Comment by xconverge** [comment]
I think regressions take priority over new features/known bugs that have been around forever.

Keeping that in mind, ones like this are easy to fix since they are fresh, and should be addressed asap, so I think whatever face you emojid was acceptable :) Then it is on us to write a test for it so that it is not a regression that happens twice ;)

**Comment by johnfn** [comment]
Yeah, not trying to be like OMG U MISUSED MY EMOJIS or something, just trying to get an idea of what people mean when they click it. 😄
