### ISSUE TITLE
Commentary toggle at start of current line comments previous line too

### ISSUE THREAD

**Issue by jgoz** [VSCodeVim/Vim#1534]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

```
    line 1
    |line 2
```

`^gbb` or `0gbb` on "line 2"

### What did you expect to happen?

Comment line 2:

```
    line 1
|   // line 2
```

### What happened instead?

Commented both lines

```
|   // line 1
    // line 2
```

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.17
* OS: macOS Sierra

**Comment by Chillee** [comment]
So I looked into the code, and it seems like the reason is that when you run the command "gbb", "gb" triggers the commenting mode, and then the second "b" jumps back a word. When the cursor is at the beginning of the word, this leads to highlighting two lines.

Can @fiedler chime in on whether this is intended behavior? I'm inclined to say no due to the README.

**Comment by Chillee** [comment]
I added a simple (not very clean perhaps) fix to this issue.

**Comment by fiedler** [comment]
Oh! It's definitely not the intended behaviour. It should stay on the same line.

Your reasoning behind why this is happening looks to be correct. I didn't experience this since I've remapped gc to gb. We should add a unit test covering this issue.

I think we need someone to look in to your PR. @xconverge can you help?

**Comment by Chillee** [comment]
@fiedler I don't like my solution very much (although I can't think of any alternatives) , as I don't think it's very resistant to keybind changes. It's possible it might work out for this specific case (I can't think of any other movement commands that can move up a line) unintentionally. 

But if, for example, the user bound gj to commenting, pressing gjj would always comment two lines.
