### ISSUE TITLE
Curly braces for arrow functions are not auto completing/pairing.

### ISSUE THREAD

**Issue by segmentationfaulter** [VSCodeVim/Vim#158]
On installing this extension, curly braces are not auto-completing/pairing for functions declarations.

**Comment by jpoon** [comment]
Auto-completing is usually a function of your IDE. Highlighting a matching brace is something in which this extension could do.

**Comment by tma-isbx** [comment]
It looks like VSCode will autocomplete (), {}, []. But with the extension only () and [] get autocompleted. {} stops working.

**Comment by johnfn** [comment]
@jpoon it sounds to me like the problem is not that we aren't autocompleting, but rather that we're inhibiting autocompletion that was previously happening. We need some way to say 'alright, we didn't handle this key, visual studio code you do whatever you were gonna do', but I couldn't find anything like that the last time I looked.

**Comment by cjowens** [comment]
@jpoon @johnfn Yes it's the plugin that is blocking VSCode's ability to autocomplete matching {} [] (), etc, when "editor.autoClosingBrackets" is set to true. However, it seems to be an issue all vim plugins have at the minute.

**Comment by hexinatgithub** [comment]
Yes,This right.Begin I think is the VSCode bug,because I begin use VSCode only a day.Then I download a new VSCode on windows, I find that all work, then I think maybe it's the plugin bug.Then I uninstall one by one, finally I find it is vim plugin.Trouble me a long time.

**Comment by johnfn** [comment]
Fixed at last!
