### ISSUE TITLE
WISH: Implement Marked Block Shift Left/Right

### ISSUE THREAD

**Issue by rickbsgu** [VSCodeVim/Vim#1611]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
Notice I can't do the following:

`:'a,'b>`

... which shifts the marked block by the indent value.  Or:

`:'a,'b>>>>`

... which shifts by multiples of the indent value.

Range shifts do appear to work:

`:.,.+n>>`

... so maybe it won't be difficult to add.  thx.

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).

**Comment by jing2si** [comment]
Shift left `<` some times not work.

**My Environment**
**OS** Windows 10
**VSCode Version**  1.12.2
**Vim Version** 0.8.1 `  "vim.enableNeovim": true`

**Comment by Chillee** [comment]
@jing2si Could you explain when it doesn't work? One thing I've noted is that if you do `'a,'b<`, mark a needs to be before mark b, otherwise Neovim will ask for a confirmation prompt.

Right now, Neovim has no method of sending this information through the API (I've talked to the neovim devs about this, and they have a solution planned), so it looks on our end like it doesn't do anything.

**Comment by jing2si** [comment]
@Chillee  Shift left get wrong indent
![1](https://cloud.githubusercontent.com/assets/2288824/26482497/60377d0a-421a-11e7-89b7-dfb1c96115f3.gif)

**Comment by Chillee** [comment]
@jing2si I know what the issue is (although I'm not completely sure how to fix it). Could you open a new issue for that?
