### ISSUE TITLE
Circumflex key does not move the cursor to the first non blank character of the current line.

### ISSUE THREAD

**Issue by Phosphor303** [VSCodeVim/Vim#1636]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.11.2
- **VsCodeVim Version**: 0.6.20
- **OS**: OS X 10.11.6

**What happened**: I pressed `^` in normal mode. vscode showed a `^` at the cursor position which disappears after the the next keypress. The cursor did not move.

![bildschirmfoto 2017-05-03 um 17 33 56](https://cloud.githubusercontent.com/assets/5774545/25668356/be26fb12-3026-11e7-8283-a33ce9d1fc15.png)

**What did you expect to happen**: I expected the cursor to go the first non blank character in the line.

**How to reproduce it**: Press `^`.

**Comment by johnfn** [comment]
This 100% has to be due to some other configuration on your computer. `^` works totally fine for me. 

Try disabling other extensions to see if that helps, or looking around for other things that might be interpreting keystrokes. I hate to say it but VSCodeVim couldn't have anything to do with this one.
