### ISSUE TITLE
g; and g, lag, off by one

### ISSUE THREAD

**Issue by lioneltay** [VSCodeVim/Vim#1824]
g; and g, allow you to go backwards and forwards in the changelist. They seem to almost work correctly but have a kind of delayed response. 

When using either command for the first time nothing happens. Then when typing either command again, the previous command will take affect.

**Example**
g;  (nothing happens)
g, (goes back, as if g; was pressed)
g, (goes forward, as if g, was pressed)
g; (goes forward, as if g, was pressed)
and so on...

**Comment by xconverge** [comment]
this should be an easy one for someone to fix

It has to do with: 
https://github.com/VSCodeVim/Vim/blob/bc36c6253e927d0c39602b0f9c796e582adac51a/src/actions/commands/actions.ts#L1960

This code is wrong somehow and needs to be fixed and then something similar added for ```"g", ";"```

**Comment by westim** [comment]
I may have a working solution for this, depending on exactly what the expected behavior is. See this commit: https://github.com/westim/Vim/commit/0ca190dbdfb95899636dc92ea01b5739cb072698

In the GIF below, I have three change positions in history: insertions at 1, 2, and 3. The GIF starts in the first change position and performs the following commands, in order:

- gg
- g; (goto position 1)
- g; (nothing happens, as expected)
- g, (goto position 2)
- g, (goto position 3)
- g, (nothing happens, as expected)
- g; (goto position 2)
- g; (goto position 1)

![gif](https://media.giphy.com/media/P7xMqkq13w0XC/giphy.gif)

Does this meet the needs for this feature?

**Comment by Chillee** [comment]
@westim I believe that looks correct.
