### ISSUE TITLE
Typing an opening or close brace triggers autocomplete menu, doesn't auto close brace

### ISSUE THREAD

**Issue by prashantv** [VSCodeVim/Vim#194]
When I type a brace (`{` or `}`), I expect the matching brace to be inserted, but instead an autocomplete menu pops up.

This makes it really hard when entering blocks (e.g. an if condition), since I typically want to type "if [condition {" followed by enter, but since the autocomplete menu pops up, the enter doesn't insert a new line but the first autocomplete selection.

![brackets-bug](https://cloud.githubusercontent.com/assets/140159/14009986/434856e2-f14e-11e5-9a56-824161b4e067.gif)

When I disable the `vim` extension, this doesn't happen. It looks like the `vim` extension causes autocomplete to be triggered constantly, even on space etc.

**Comment by jpoon** [comment]
Thanks for reporting the issue! I'm going to close as a duplicate in favor of https://github.com/VSCodeVim/Vim/issues/158 as that was filed first :).

This is inherently due to how VSCode handles extensions, their updated extension APIs in 0.10.12, but we'll need to do work to update to those APIs as well which is tracked by https://github.com/VSCodeVim/Vim/issues/188.
