### ISSUE TITLE
Scrolling with CTRL-E is very slow

### ISSUE THREAD

**Issue by vsobotka** [VSCodeVim/Vim#1943]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.15.0-insider
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

**What happened**: Scrolling down with `CTRL-E` by more than two lines makes the scroll very slow. While the scrolling itself is very slow, you have to wait until it catches up to where it was supposed to scroll based on the time the keys were pressed. For example, pressing `CTRL-DOWN` for 2 seconds makes the scroll 2 seconds long, scrolling down by 100 lines. Pressing `CTRL-E` for 2 seconds makes the scroll 6 seconds long, scrolling down by 100 lines. 

**What did you expect to happen**: I expect the `CTRL-E` and `CTRL-DOWN` to scroll with equal speed.

**How to reproduce it**: Open a file with enough lines to scroll through and compare `CTRL-E` and `CTRL-DOWN`.

**Comment by Chillee** [comment]
To be clear, `ctrl-down` and `ctrl-e` have a bit different behavior. `ctrl-down` scrolls the screen without moving the cursor, while `ctrl-e` scrolls the screen while keeping the cursor at the bottom or the top.

**Comment by alexdreptu** [comment]
I'm experiencing the same problem with both ctrl+e and ctrl+d, but have no issue with ctrl+down.

- VSCode Version: 1.14.2
- VSCodeVim Version: 0.9.0
- OS: Arch Linux

**Comment by kconner** [comment]
I reproduce with ctrl-E, ctrl-Y, ctrl-D, and ctrl-U.

VSCode Version: 1.15.0 (1.15.0)
VSCodeVim Version: 0.9.0
OS: macOS Sierra 10.12.6 (16G29)

**Comment by Viker** [comment]
I am also struggeling with a incredible lag while scrolling.

**Comment by kennym** [comment]
So, in my case it was because of Rubocup running... I deactivated it, now everything works.

**Comment by mattscully** [comment]
@Chillee For me, `ctrl-down` and `ctrl-e` have the exact same behavior.  The cursor stays on the same line in the file and the window scrolls.  The only difference is that *holding down* `ctrl+e` is super slow.  Note, for me, the key is holding down `ctrl-e`.  If I press it fast, it works fine.  This is because the keyboard auto-repeat when holding down a command is much faster than what I can push manually.  When I hold down `ctrl-down`, the window scrolling keeps up with the auto-repeat behavior.

VSCode Version: 1.20.1
VSCodeVim Version: 0.11.0
OS: windows 10

**Comment by RRethy** [comment]
ctrl-e/ctrl-y/ctrl-u/ctrl-d are all super slow when holding it down and won't let me do anything for another second since the buffered inputs all still need to finish. I just started trying out vscode so this is the only plugin I have installed so nothing else could be screwing it up.

VSCode Version: 1.20
VSCodeVim Version: 0.11.0
OS: MacOS Sierra v.10.12.6
