### ISSUE TITLE
    "<C-d>": false, has not efect

### ISSUE THREAD

**Issue by metasong** [VSCodeVim/Vim#1947]
"<C-d>": false, has not effect

**Comment by zmoazeni** [comment]
I believe I figured out the issue is this line: https://github.com/VSCodeVim/Vim/blob/bee6ac6088223efd6596ccae547b263d21145f36/package.json#L91

which was changed in https://github.com/VSCodeVim/Vim/pull/1631

It looks like adding `&& vim.use<C-d>` causes other problems that the PR fixed. 

So I had to open up the keybindings, searched for `vim_ctrl+d` and deleted the key binding.

**Comment by granteagon** [comment]
Seeing the same issue, which is not allowing the [new Ctrl-D](https://github.com/Microsoft/vscode/issues/8869) functionality to work correctly.

**Comment by jpoon** [comment]
Should be fixed with https://github.com/VSCodeVim/Vim/pull/2269. See the table in the PR about the expected behaviour.
