### ISSUE TITLE
Multi-cursor append line above (Shift+O) only works for 1 cursor

### ISSUE THREAD

**Issue by tomasiser** [VSCodeVim/Vim#1962]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.2
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

**What happened**:

1) be in normal mode
2) using Alt+leftclick, create cursors at multiple lines
3) press Shift+O
4) a new line is appended only above the first cursor

**What did you expect to happen**: 

4) new lines are appended above all cursors

(**note:** it already works correctly when appending below with O instead of above with Shift+O)

**How to reproduce it**:

see What happened

**Comment by cvaldev** [comment]
I looked into this one and found that the line below causes VSCode to loose our selections temporarily just before executing `editor.action.insertLineBefore`.

https://github.com/VSCodeVim/Vim/blob/98f3242bc7ad8f1804a0a96791386456d72d76df/src/actions/commands/actions.ts#L2646

Updating all selections rather than just the main selection would solve this issue. However, it appears the issue referred to in https://github.com/VSCodeVim/Vim/pull/1663#issuecomment-300573129 has been resolved in the upstream. I couldn't find anything on the VSCode repo that mentions how they solved it, unfortunately.
