### ISSUE TITLE
Cant remap keys for operators

### ISSUE THREAD

**Issue by ghost** [VSCodeVim/Vim#2041]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**FEATURE REQUEST**:
Apply otherModesKeybindings to operator mode, like omap in Vim. (When pressing `c` for example, it waits for more operators)

**Environment**:
- **VSCode Version**: 1.16.1
- **VsCodeVim Version**: 0.10.1
- **OS**: ArchLinux

**What happened**:
I have my hjkl keys remapped to hnei (I use the colemak layout). When for example pressing `c` and then `i` to change the character on the right, it instead interprets it as `inside`.

`e` is mapped to `m`, and when pressing `cm` I except it to change to the end of the word, but it instead waits for a mark name.

**What did you expect to happen**:
Explained above

**How to reproduce it**:
Change keymap of some movement key to something else and try to use it in operator mode.

**Comment by Chillee** [comment]
This is an unfortunate consequence of the way our remapping system is implemented.

**Comment by paxy97** [comment]
Is it fixable? Since it pretty much makes vim a pain to use :/

**Comment by Chillee** [comment]
@paxy97 Unluckily, I'd have to suggest not using vscodevim if you use colemak. Our current rebinding system simply isn't reliable/comprehensive enough to ensure a good experience. Check back in perhaps half a year: https://github.com/VSCodeVim/Vim/pull/1897 would be able to fix your issue.

**Comment by paxy97** [comment]
That looks promising. I switched to sublime, since the actualVim plugin uses neovim and works quite well, except for completion. So this switch to Neovim for VSVim might actually make the perfect editor if everything goes as planned. Looking forward to that.

**Comment by Chillee** [comment]
@paxy97 Tell me how your experience with ActualVim goes, I'd like feedback on what it does well/poorly/what its limitations are for doing VSCodeNeovim.

**Comment by paxy97** [comment]
Well, if I understood correctly, you're trying to achieve a similar thing. Have Neovim run in the background with the buffer open and interact with vscode in regards to cursor position, selected text etc.

ActualVim does the same thing, except that it also uses Vim's completion (which I don't prefer) and passes every single keystroke to Vim. So for example Vim captures ctrl+o and does nothing with it, so sublime can't use it to open the open file dialog.

So it would be nice if I could configure the keys that I don't want passed (mostly control+something). Kind of like what you're doing already.

What I like that it behaves in the same way as if I had opened a Vim instance, so all my plugins and keybindings just work without the need to remap everything and look for replacement plugins that may or may not work as expected.

A limitation might be the completion. I have no idea how either the VS code, or the sublime one are implemented. But one drawback of actualvim is that using it breaks sublime's autocomplete and only uses the vim one, even the keybindings. This is the most annoying thing, since I do a lot of JS development, or to be more accurate, VueJS. And vim does not seem to have a good js completion that works across files and classes, at least not one that I have found. So I'm currently looking how to work around that issue.

**Comment by Chillee** [comment]
@paxy97 I was more just curious what kinds of bugs you've found/limitations you've run into. This is something I've been working on for several months now, so I definitely understand many of your concerns.

> ActualVim does the same thing, except that it also uses Vim's completion (which I don't prefer) and passes every single keystroke to Vim. So for example Vim captures ctrl+o and does nothing with it, so sublime can't use it to open the open file dialog.

> So it would be nice if I could configure the keys that I don't want passed (mostly control+something). Kind of like what you're doing already.

Not completely sure how we'll handle this, but we will definitely handle it in a way that satisfies this requirement.

> A limitation might be the completion. I have no idea how either the VS code, or the sublime one are implemented. But one drawback of actualvim is that using it breaks sublime's autocomplete and only uses the vim one, even the keybindings. This is the most annoying thing, since I do a lot of JS development, or to be more accurate, VueJS. And vim does not seem to have a good js completion that works across files and classes, at least not one that I have found. So I'm currently looking how to work around that issue.

In my opinion, autocompletion/IDE'ish features are a very large part of the reason anybody even uses VSCode in the first place. This is something that's been very hard to get right, but I think that I've finally gotten it right (it works very well for me during testing).

Creating a vim extension backed by neovim has a lot of decisions put into it, which is why I was curious about how satisfied you were with the decisions made by ActualVim.

**Comment by paxy97** [comment]
If I find the time I can try building it and see if I can so far find room for improvement :)

**Comment by Chillee** [comment]
@paxy97 I'm about to make a new repo and provide a .vsix for download there, so just wait for that :)

**Comment by paxy97** [comment]
One more thing, there seem to be some issues with autoindent. I haven't been able to figure out what causes it or how to fix it, but I just thought I'd tell you to keep it in mind when testing :)

**Comment by rtorresware** [comment]
Damn... I'm going to have to switch extensions as well

**Comment by ohjames** [comment]
@clamb @rtorresware @ghost Did any of you find a vs code vim extension that does work well with colemak? I've been trying to fix colemak issues with VSCodeVim for a while but it's hard... some of the code is using a facade around certain VS Code functionality, and then other bits of code access the exact same functionality without a facade. You can't just fix the issues in one place, in the facade, you need to apply certain keybinding related fixes to two places.

**Comment by rtorresware** [comment]
@ohjames no, I haven't found one yet. A possible workaround would be to allow remapping of dj, dk, yj and yk

**Comment by ohjames** [comment]
@PKeves still open and not working

**Comment by ollyhayes** [comment]
I wonder if it's possible to fork the repository and remap the keys where they're defined in the plugin rather than using the configuration to remap? Has anyone thought about that or tried it? If not I might have a go. I was goingo to start [here](https://github.com/VSCodeVim/Vim/blob/093857300e85f788f561b31e2f25906a461fee2e/src/actions/motion.ts) and see how I get on...

**Comment by ollyhayes** [comment]
I wonder if it's possible to fork the repository and remap the keys where they're defined in the plugin rather than using the configuration to remap? Has anyone thought about that or tried it? If not I might have a go. I was goingo to start [here](https://github.com/VSCodeVim/Vim/blob/093857300e85f788f561b31e2f25906a461fee2e/src/actions/motion.ts) and see how I get on...
