### ISSUE TITLE
Unable to close windows in normal mode with ctrl-w

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#2056]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

vscode ticket: https://github.com/Microsoft/vscode/issues/35753

**Environment**:

- **VSCode Version**: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- **VsCodeVim Version**: 0.10.1
- **OS**: Ubuntu 16.04

**What happened**:

1. Open a file
2. ctrl-w
3. File was not closed (note: modified files did not display the "save first?" dialog)

*Note*: I was in normal mode while testing this. If I were in insert mode this obviously would have a different result.

**What did you expect to happen**: 

The file would be closed (and I'd be prompted to save if the file was modified).

**How to reproduce it**:

See steps above.

**Comment by xconverge** [comment]
Please add the following to your settings.json to delegate the keystroke BACK to vscode since Ctrl+w is a vim keyboard command that we use.

```
    "vim.handleKeys": {
        "<C-w>": false
    }
```

Please reopen if you have any further issues

**Comment by Phrohdoh** [comment]
But that blanket change isn't correct.

Normal-mode C-w should close the window but Insert-mode C-w should delete a word backwards.

**Comment by xconverge** [comment]
C-w is a vim command, you can either choose to use it or delegate it back to vscode. I think if we fracture it further and allow you to disable certain keys in certain modes it is going to start to get pretty complicated. Feel free to open an issue for that though!

The vim way is to use :q or :x

You could also rebind vscode's close window command potentially to another combination, but I understand the appeal of C-w since I add the disable C-w command on windows/linux personally

**Comment by Phrohdoh** [comment]
That's a fair stance to take. Thanks for the timely response!

**Comment by xconverge** [comment]
A feature request to allow handleKeys to also take a mode is fine though! Don't get me wrong!

In general we are going to try to move towards true vimrc support with neovim integration etc, so I want to try and focus on stability first, open the feature request though if you will use it!

**Comment by tagirb** [comment]
> The vim way is to use :q or :x

Or also `C-w q` `C-w c`.

**Comment by Eksapsy** [comment]
> The vim way is to use :q or :x

Yes indeed, I doubt though that many users haven't changed `:q` to just a `leader` command for the sake for doing it faster.

> C-w is a vim command, you can either choose to use it or delegate it back to vscode. I think if we fracture it further and allow you to disable certain keys in certain modes it is going to start to get pretty complicated. Feel free to open an issue for that though!

But in this case though, I think it would feel more natural to have both. It's not like `Ctrl+W` is anymore useful in **normal mode**, is it? So why not just use it for default VSCode behavior?

I really felt that it was a bug and unnatural because it felt very unnatural for an unused vim binding to not be used for default VSCode keybindings. And from what I see, I was not the only one.

I feel like there could be added at least some guide into implementing this behavior for users who want to.

**Comment by xconverge** [comment]
Sorry but C-w is not an unused vim binding, it is very much mapped and used. Am I understanding correctly? is handleKeys with C-w : false not sufficient?

**Comment by tzohpilotl** [comment]
This caused me much confusion when changing from my Mac to my PC because in Mac you would do CMD+w to close the tab. I expected to translate that behavior just by swapping the use of CMD to CTRL on Windows but it seems like it's not going to work that way.

**Comment by J-Fields** [comment]
Yeah, vim on mac is nice because using cmd for application shortcuts doesn't conflict with vim keybinds with ctrl. You can always do what I do:

`nnoremap <C-w> workbench.action.closeActiveEditor`

**Comment by rohitchormale** [comment]
Below settings may help. It will close active-editor WITHOUT SAVING. If you want to save and close, then first do 'ctrl-s' and then 'ctrl-w'

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-w>",],
            "after" : [":", "q", "!", "<enter>"]
        }
    ],

```

**Comment by nviennot** [comment]
```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-w>",],
            "commands" : ["workbench.action.closeActiveEditor"],
        }
    ],
```
