### ISSUE TITLE
VIM not working?

### ISSUE THREAD

**Issue by resting** [VSCodeVim/Vim#2231]
**Environment**:

- **VSCode Version**: 1.19.0 (1.19.0)
- **VsCodeVim Version**:  0.10.6
- **OS**: 10.13.2 (17C88)

**What happened**:
Just opened some text and js files with VSCode and realize VIM isn't working anymore.
I can't get into command mode. Anyone else having this problem?

**Comment by rajinder-yadav** [comment]
It has stopped working for me too. I've been using this for a long time with no issues. I've tired reinstalling, reboot, etc nothing works.

- I am also using vs code insiders `Version 1.20.0-insider (1.20.0-insider)`.
- Vim 0.10.6
- MacOS 10.13.2

**Comment by jpoon** [comment]
See https://github.com/VSCodeVim/Vim/issues/2227 and https://github.com/VSCodeVim/Vim/issues/2226

**Comment by rajinder-yadav** [comment]
@jpoon your suggestions don't work. this plugin has occurring issues that I've just decided to finally  switch.

**Comment by rajinder-yadav** [comment]
@jpoon suggestion 2226 worked for me. Happy again, thanks! :-) 👍

**Comment by jpoon** [comment]
In general, it would be super helpful when filing issues to be more descriptive than "it doesn't work". I can't repro this so I'm not sure how I can help you debug this. What steps have you tried? Do you see anything in the console log? 

> this plugin has occurring issues that I've just decided to finally switch.
Please be mindful that this is a project is maintained by a group of volunteers. We aren't being paid, and are doing this on our spare time.

**Comment by rajinder-yadav** [comment]
I suggest all volunteers really test new feature, fixes, code changes, etc before rolling it out. This would go a long way to prevent continued issues that pop up and disappear.

**Comment by rajinder-yadav** [comment]
Thank you for your hard work!

**Comment by jpoon** [comment]
> I suggest all volunteers really test new feature, fixes, code changes, etc before rolling it out. This would go a long way to prevent continued issues that pop up and disappear.

We have automated builds and tests. What would you suggest? What "continued issues" are you seeing?

**Comment by rajinder-yadav** [comment]
Well this issue just happened again, right now. So I am not sure what is causing this plugin to keep failing. I assume vscode does auto-update of the plugin and something keep going wrong with this plugin.

Also in the past I've see it get confused with the explorer window, and I am unable to type certain keys like 'o' or other VIM released command when I right-click to create a new file. I usually put up with it and just drop in the terminal to create a new file.

However would be nice to know why vim stops working for 2nd time in the same day I used your suggestion earlier.

Can we reopen this issue till possibly the issue is tracked down and fixed for good, rather then some workaround that doesn't seem to do any good.

**Comment by rajinder-yadav** [comment]
So I did a clean reinstall, the vim plugin version is still the same 0.10.6
Also I didn't update anythings on my end, still use vscode insider, `Version 1.20.0-insider (1.20.0-insider)`.

The plugin was working find, what I last recall going was switching to the vscode terminal, doing a, `npm i`, when I switch back to the editor vim stop working.

I will continue to monitor on my end for vim plugin fails for some odd reason. It could be some other bug in vscode, in which case it might be  a good idea later to open a bug with them.

**Comment by hasan-sh** [comment]
I had the same. On Ubuntu. Just upgraded and it worked afterwards.
