### ISSUE TITLE
vim.leader with comma does not work

### ISSUE THREAD

**Issue by jimzhan** [VSCodeVim/Vim#2257]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**What happened**:
`vim.leader=,` does not work properly, it constantly waits for the second key even under `Insert` mode, thus, I can't type "," in my editor under `Insert` mode. (`vim.leader=<space>` works fine in the meantime).

**What did you expect to happen**:
`vim.leader=,` should be available only under `Normal` mode.

**How to reproduce it (as minimally and precisely as possible)**:
- add `vim.leader=,` to `settings.json`.
- switch to `Insert` mode in editor.
- try type `,`.

**Environment**:
- MacOS

- Extension (VsCodeVim) version: v0.10.6
- VSCode version: v1.20.0-insider
- OS version: macOS High Sierra v10.13.2

**Comment by chrisarcand** [comment]
For posterity:

I also had this issue, and discovered it was because I had _just_ mapped `,t` in keyboard shortcuts to gotoFile as I want that functionality to exist even when I don't have an editor group (or, 'buffer') open. But then VSCode intercepts the chord before the extension. It's VSCode, and not this extension, waiting for the chord.

My attempts to get VSCode to acknowledge ',t' when an editor isn't open by using a when clause are also unsuccessful as VSCode still swallows the binding and then no leader commands work with this extension.
