### ISSUE TITLE
'Searching for:' not showing actual search string

### ISSUE THREAD

**Issue by evenfrost** [VSCodeVim/Vim#2261]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
When searching with <kbd>/</kbd>, VSCode status bar shows `--SEARCH IN PROGRESS-- Searching for:` but doesn't show string currently being searched. 

**What did you expect to happen**:
Bottom bars shows string entered for search.  

**How to reproduce it (as minimally and precisely as possible)**:
![sample-search](https://user-images.githubusercontent.com/3055750/34567902-1cc64dfc-f175-11e7-8cad-e25529e76e70.gif)

**Environment**:

- Extension (VsCodeVim) version: Sunny Seattle
- VSCode version: 1.19.1
- OS version: Ubuntu 17.10

**Comment by jpoon** [comment]
Hm, sounds like a regression.

**Comment by intijk** [comment]
I confirm this bug. 

By the way, is there any way to remove the display of 

`--NORMAL MODES--`   to nothing 

and 

`--SEARCH IN PROGRESS--`  to a simple `/`

**Comment by jpoon** [comment]
@intijk the regression has been fixed in master. I agree with you on the `search in progress` thing and was thinking of changing it -- thanks for validating that.

**Comment by intijk** [comment]
Glad to see your fast integration! I saw the change in the code-insiders now. 

How about simplify the display further

1. in normal mode, display nothing 
2. in other mode , remove 'mode' word,  `-- INSERT --` instead of `-- INSERT MODE --`
3. I don't know if this possible, but good to have, that is to make the ':' mode also display content on bottom, instead of display a floating command window.

**Comment by jpoon** [comment]
> saw the change in the code-insiders now.
It doesn't matter what vscode you are running. I shipped out a new version last night so that's probably why you see it.

> 1. in normal mode, display nothing
I'd prefer to keep `-- NORMAL --` as that's an indication that the vim extension is loaded, and also prevents any vim beginner-eque questions about "what mode am i in?"

> 2. in other mode , remove 'mode' word, -- INSERT -- instead of -- INSERT MODE --
Yeah, agreed.

> 3. I don't know if this possible, but good to have, that is to make the ':' mode also display content on bottom, instead of display a floating command window.
Not do-able. there's a bug somewhere on our issue list about this, but it's reliant on VSCode APIs.
