### ISSUE TITLE
:edit command gives ENOENT error

### ISSUE THREAD

**Issue by slurps-mad-rips** [VSCodeVim/Vim#2422]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: I use `:e` quite a lot in my vim workflow. As of about a week ago (as I understand it, v0.11.0 was just released), I receive the following error:

![screenshot 2018-03-05 15 04 57](https://user-images.githubusercontent.com/63051/37004854-bacc4624-2086-11e8-93f0-b9f66939763c.png)

**What did you expect to happen**:

Typically, if the file exists, it is opened. If it is not, VSCodeVim asks if I would like to create the file (I should note this deviates from Vim's behavior, which is to open a buffer with the filename, but that is outside the scope of this bug)

**How to reproduce it (as minimally and precisely as possible)**: Open any file, then press `:e any-file-name`. The error is then displayed. It's obviously placing the drive root in the path twice, which will cause an error.

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Windows 10 Pro Version 1709

**Comment by jpoon** [comment]
> Typically, if the file exists, it is opened. If it is not, VSCodeVim asks if I would like to create the file (I should note this deviates from Vim's behavior, which is to open a buffer with the filename, but that is outside the scope of this bug)

That issue (https://github.com/VSCodeVim/Vim/issues/2274) was fixed with https://github.com/VSCodeVim/Vim/pull/2392. However, there was a regression reported with https://github.com/VSCodeVim/Vim/issues/2408 and later fixed with https://github.com/VSCodeVim/Vim/pull/2409 about overwriting the file.

The bug you reported is a Windows pathing issue. Fix incoming...
