### ISSUE TITLE
Implement `:m[ove]` command

### ISSUE THREAD

**Issue by kimfucious** [VSCodeVim/Vim#2472]
**FEATURE REQUEST**

Hi there, 

I've perused the road map and couldn't find :copy and :move commands.  I also couldn't find a decent way to replicate these using native VS Code commands.

I believe that any Vim user would love to see these implemented in your *already fantastic* extension.

"The vim :copy command (and its shorthand :t) lets us duplicate one or more lines from one part of the document to another, while the :move command lets us place them somewhere else in the document."

The format of the copy command goes like this:

`:[range]copy {address}
`

The :move command looks similar to the :copy command:

`:[range]move {address}
`

**Reference:**
“Practical Vim: Edit Text at the Speed of Thought.” Practical Vim: Edit Text at the Speed of Thought, by Drew Neil, The Pragmatic Bookshelf, 2012, pp. 59–61.

**Environment**:

- Extension (VsCodeVim) version: 0.11.2
- VSCode version:  1.21.1 (1.21.1)
- OS version:  10.13.4 Beta (17E182a)

**Comment by caleywoods** [comment]
Came here looking for this. Today I had an instance where I wanted to move a line of code that was 21 lines below my current cursor position and paste it onto the line where my cursor was. In Vim you can accomplish this with command mode and `:+22m.` to move the line `22j` down to your cursor position.

Entering `:+22m.` into Vimcode's command thing right now has no effect.

**Comment by jpoon** [comment]
I believe this should work with the neovim integration.

**Comment by caleywoods** [comment]
@jpoon Thank you, I will get this set up this weekend and give it a try. Have a great weekend.

**Comment by caleywoods** [comment]
@jpoon Not seeing this working quite yet. I have Neovim set up correctly. I have tried having the `neovimPath` set as the absolute path and as just `nvim` with having `C:\Program Files\Neovim\bin` in my path. I get no errors when launching VSCode about spawning neovim like I previously did when I forgot the `bin` part of the path. I double checked the neovim functionality by executing a `:{range} norma d2w` across some example text from a vi stack exchange post and it worked.

With neovim installed, enabled in vscode, executing `:+{line number}m.` has the same behavior as before where nothing happens, the line is not moved to the cursor position. I have included the image below showing nvim being ran in Cmder (via just executing `nvim` since it's in the path) and my neovim settings in vscode.

I can move it with `:{absolute number}m.` but `:+{relative number}m.` does not work in vimcode while I verified it does work in vim/neovim. Is there a way for me to debug what might be going on so I can maybe help get it to actually work?

![image](https://user-images.githubusercontent.com/402957/41510192-b15d0600-7225-11e8-87be-07b792708003.png)
on

**Comment by xlucas** [comment]
Any update on this being supported?

**Comment by zkerhcy** [comment]
Notice that the `copy` command has been implemented, Looking forward to using the `move` command.

**Comment by Miigon** [comment]
Is this still on the roadmap?

**Comment by dannoe** [comment]
When will a new version be released that includes this change?
