### ISSUE TITLE
Can't bind leader key shortcuts to some vscode methods

### ISSUE THREAD

**Issue by deerainw** [VSCodeVim/Vim#2674]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**What happened**:
Failed to bind `workbench.action.navigateBack` to `<leader> j b`

My setting:
```json
        {
            "before":["<leader>","j","b"],"after":[],
            "commands": [
                {
                    "command": "workbench.action.navigateBack",
                    "args": []
                }
            ]
        },  // jump back
```

The original shortcut `alt + left arrow` works fine.

**Environment**:

- Extension (VsCodeVim) version: the latest version
- VSCode version: the latest version
- OS version: windows 7

**Comment by trsdln** [comment]
Binding like

```
    {
      "before": [
        "leader",
        "r"
      ],
      "after": [],
      "commands": [
        {
          "command": "editor.action.rename",
          "args": []
        }
      ]
    },
```

stopped working recently as well.

**Comment by jpoon** [comment]
Likely due to the change we made in v0.13.0 https://github.com/VSCodeVim/Vim/blob/master/CHANGELOG.md#v0130-2018-06-18.

Please note that we've also added more debugging (https://github.com/VSCodeVim/Vim#vimdebuglogginglevel), so you can take a look at what keys we've registered for remapping and what keys are being passed to the extension from vscode.
