### ISSUE TITLE
Long key chords does not trigger configured action.

### ISSUE THREAD

**Issue by regiontog** [VSCodeVim/Vim#2735]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug
**What happened**:
With a long key chord like ```['<leader>', 'f', 'e', 's']``` configured, VSCodeVim  interpret `['<leader>', 'f', 'e']` and `['s']` as separate actions. The command bound to the key chord does not execute.
**What did you expect to happen**:
Expected the bound command to execute.

**How to reproduce it (as minimally and precisely as possible)**:
See unit test in 21659e7239d99f6d6f4fd454fd1a773964c62708

**Environment**:

- Extension (VsCodeVim) version: 0.12.0
- VSCode version: 1.24.0
- OS version: Linux 4.15.12

**Relevant issues**
#1405

**Comment by jpoon** [comment]
I ran into this issue earlier. I think it's because `vim.leader` is being remapped using a key for an existing vim command. For instance, in the UT that you had created:

before: `,fes`
after: `v`

When you press `,` (which is the leader key), we will immediately execute: https://github.com/VSCodeVim/Vim/blob/9cff13d43d40e2b3e717f0234ff7520338030747/src/actions/motion.ts#L749 and not wait for further keys.
