### ISSUE TITLE
(feature) Add an option to bring commandline back to old place 

### ISSUE THREAD

**Issue by hastebrot** [VSCodeVim/Vim#2773]
https://github.com/VSCodeVim/Vim/pull/2758 (released in v0.14.0) moves the commandline to the status bar to allow history navigation.

This forces me to activate the status bar.

It would be nice if there is an option provided to configure the place of the commandline.

**Comment by xconverge** [comment]
Are you ok without history navigation? Apologies for breaking your workflow

**Comment by jpoon** [comment]
I was discussing this on Slack earlier, was that you @hastebrot that I was talking to?

What is your motivation for wanting to use VSCode's input box for the command line (ie. old behaviour)? The current implementation of placing the command line in the status bar is more vim-like and due to @xconverge 's great work, supports history navigation (which is something that the Input Box would not support). I'd much rather try to get the current behaviour working to whatever your (@hastebrot) workflow is rather than having to support two ways of inputting VIM commands.

**Comment by xconverge** [comment]
I will see if I can come up with something minimal tonight, another case where this could be useful is zenmode

**Comment by hastebrot** [comment]
@jpoon No, wasn't me.

@xconverge I'm fine without history navigation.

**Comment by jpoon** [comment]
> I don't want to configure every plugin or change the color of the statusbar. VSCode's input box is a fine place for me.

Not to be pedantic, but with the commands shown in the status bar, it takes up the equivalent amount of space. Instead of `-- NORMAL --` you would see your VIM command (e.g. `:wq`)

I don't use zenmode so not sure what I'm missing out there or what that means.

**Comment by mindgitrwx** [comment]
It should be placed on command palette for people who uses zen mode.

**Comment by hastebrot** [comment]
In my setup I deactivated the status bar and the activity bar because they distract me. The menu entries to deactivate them are directly in the `view` menu, so it seems to be an important use case for others.

>it takes up the equivalent amount of space

I see. It changes from `-- NORMAL --` to the typed `:` command. But I really only want to have my editor view and optionally open a quickpick, or `projects`, `extensions` view in the sidebar, and close it afterwards.

So far it worked for me to disable the status bar without downsides, e.g. the current git branch is shown in the status bar, but I can also list the current branch along other branch using "Git: Checkout to..." which opens a command quickpick menu. I also don't have to look into the status bar to see the current Vim mode, since the cursor also changes to indicate whether I'm in `command`, `normal`, or `visual` mode.

**Comment by jpoon** [comment]
I'm not familiar with zen mode, in vanilla vim, where do you see the commands when you are in zen mode?

**Comment by Samonitari** [comment]
Hi all!

Excuse me for chiming in! First, thanks for your awesome work, it is great stuff!

I'd like to vote for the previous location too - I mean make an option for it.
For me it is just more ergonomic the "old way". Status bar is a thing I rarely glance upon, and largely outside of my vision. Checking what I type in a complicated regex is quite uncomfortable, with the default size of statusbar - is it even resizeable? I think the name - status bar - says it all. It is mostly "static" information, that does not change with every key I press (or not that relevant), more dynamic thing should be placed closer to the code. If integrated-terminal/output/debug-console is open, editor is even further from the command I'm typing _for the editor_

I think vim, neovim is great (haven't used vi, I am not that old)! But! They come from an age where all, but the most simple ui was possible - you can't/couldn't bring up popups in terminal(emulator)s. 
So code is on the big screen, all other info is at the bottom line. But for me, that is a technical limitation that you should not reproduce, because that is the "historical" way.
By the way, the neovim-based editor [oni](https://github.com/onivim/oni) is opted for a command-palette like placement of the command-line too. That is what I use for little edits on workplace windows systems.

I hope that you don't think it is a rant - absolutely not! I will continue to use your project even if you don't implement it, and the command history is great! Maybe I am in the wrong regarding better ergonomics, but if you think about it/ask some people that would be great!

**Comment by mindgitrwx** [comment]
The zen mode I mentioned was not zen mode in vim, but zen mode in vscode. Before I started using vim, I became familiar with the basic functions of vscode, and I found out about the convenience of vim and installed the vscode vim plugin. In the previous version, in zen mode, when I typed the colon, the command I typed  showed up at the top of the screen. So I can use it without feeling any inconvenience. 

Zen mode is very useful when you have a vertical monitor.

**Comment by jpoon** [comment]
Looks like @xconverge merged the fix in and added this relevant doc: https://github.com/VSCodeVim/Vim#how-can-i-use-the-commandline-when-in-zen-mode-or-when-the-status-bar-is-disabled

I want to clarify that with the quick pick it does *not* and will *not* support: 

* history navigation (pressing up/down to get the previous/next commands)

**Comment by xconverge** [comment]
There is another fix in the pipeline for this

#2816

**Comment by hagabaka** [comment]
Besides the lower visibility, the status bar command input also doesn't let you use arrow keys to move the cursor (it doesn't even show a cursor), or copy from/paste into it. I do appreciate the ability to navigate in history though.

**Comment by xconverge** [comment]
@hagabaka there are vscode upstream issues already filed for quickpick improvements, they have been filed for over a year with quite a few thumbs ups (https://github.com/Microsoft/vscode/issues/23633)

you can paste into the commandline currently fyi, C-v and Cmd-v will paste!

**Comment by hagabaka** [comment]
Ah, Ctrl-V does work. I was trying Shift-Insert before since I use Ctrl-V for visual block selection.

**Comment by me-nkr** [comment]
Also when the commands are long there's not enough space in status bar. I just set `:` to bring up vim command line in vs code command palette, but it does not have history option 😭

**Comment by me-nkr** [comment]
Well I found a hack around solution though, you can set `Vim: Show Command Line` to `Shift + .` and set its when expression to `editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'command'`. So now if you need the command palette you could use `Shift + .` or you can use the one in status bar for history and short commands.

I don't know if this will work for zen mode though

Also I find it confusing why setting `Vim: Show Command Line` to `Shift + .` creates another keybinding `Shift + <` for the same.
