### ISSUE TITLE
Select text from current position to end of line

### ISSUE THREAD

**Issue by frankyuan** [VSCodeVim/Vim#2819]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT (not sure)
**What happened**:
When I'm trying to select text from current position to end of line, I use v$, the cursor jump to the begin of next line.
**What did you expect to happen**:
The cursor should be in end of line.
**How to reproduce it (as minimally and precisely as possible)**:
In normal mode, at the middle of text, type v$, you will see the cursor jump to the next line.

**Environment**:

- Extension (VsCodeVim) version:0.14.2
- VSCode version:1.25.0
- OS version: windows 10

**Comment by urbpeti** [comment]
It just shows the cursor in the next line but it is on the new line symbol. Maybe it is because of VsCode. If you press the 'l' key after 'v$' it will not step right. You can see the different if you go to visual mode navigate to the last character in the line and press space bar. After that you can step right, because you are in the next line's first character.

**Comment by frankyuan** [comment]
Thanks for your feedback! If I press 'd' key after 'v$', the next line's content will join to current line.

**Comment by snackycracky** [comment]
also when I yank, then it will yank the linebreak at the end as well. Vim in the Terminal does not show that behavior.

**Comment by J-Fields** [comment]
@snackycracky Really? I just tested in vim and neovim and they both showed this behavior.

This has come up several times in the past. `v$` includes the newline, so `v$d` should not behave like `d$`, for instance. Until someone demonstrates that I'm wrong about this, I'm closing the issue as `by-design`.
