### ISSUE TITLE
Clicking end of line with mouse sometimes selects empty character

### ISSUE THREAD

**Issue by chrisblossom** [VSCodeVim/Vim#3260]
**Describe the bug**
When using a mouse to select a line, an empty character is sometimes selected at the end of the line instead of the last character.

**To Reproduce**
Click far right of lines until selected character is empty

**Expected behavior**
Cursor is at last character

**Screenshots**

![vscode vim eol mouse example](https://user-images.githubusercontent.com/1595871/49907602-b8aa0880-fe2b-11e8-9d53-5e1923106ef7.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.14
- VSCode version: 1.29.1
- OS: MacOS 10.14.1

**Additional context**
Only happens with mouse, I'm unable to reproduce with touchpad.

**Comment by EtiamNullam** [comment]
I was about to comment on this issue a long time ago and it's still valid.

The empty character gets selected when you **drag** (even slightly, in any direction), and you probably did that by accident when clicking around ;)

![SVKk0Ky701](https://user-images.githubusercontent.com/10875340/68094769-fe3c4d80-fea3-11e9-9398-2300f2c08460.gif)

Also that's why you its impossible to reproduce with touchpad - you have to double-tap to drag using it.
