### ISSUE TITLE
Unhandled rejection. Promise [object Promise]. Reason: TypeError: Cannot read property 'trim' of undefined.

### ISSUE THREAD

**Issue by gazedash** [VSCodeVim/Vim#3328]
**Describe the bug**

> Unhandled rejection. Promise [object Promise]. Reason: TypeError: Cannot read property 'trim' of undefined.

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by jpoon** [comment]
To provide context on why you are now seeing this error, is that with v1.0.0, we've decided to show vim extension errors as these alerts so that it would be easier for users to identify errors when vscodevim is misconfigured (ie. remappings, neovim) or when things are not working as expected. We've always logged it to the console, but this wasn't very discoverable. The related configurations are below if you would like to go back to the old behaviour of living in bliss/ignorance of these errors 😅 :

Setting | Description | Type | Default Value
-- | -- | -- | --
vim.debug.suppress | Boolean indicating whether log messages will be suppressed. | Boolean | false
vim.debug.loggingLevelForConsole | Maximum level of messages to log to console. Logs are visible in the developer tools. Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error
vim.debug.loggingLevelForAlert | Maximum level of messages to present as VS Code information window.  Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error

----

In terms of your error, how can you reproduce this?

**Comment by IAIAE** [comment]
same.

Extension (VsCodeVim) version:  1.0.0
VSCode version:  1.30.1 (1.30.1)
OS:  mac os high sierra 10.13.6

**Comment by IAIAE** [comment]
![image](https://user-images.githubusercontent.com/11187162/50733663-90b08980-11cc-11e9-813b-66f3b45581e2.png)

set silent 'true', also show the log. a bit annoying
