### ISSUE TITLE
Unhandled rejection. Promise [object Promise]. Reason: Failed to execute git

### ISSUE THREAD

**Issue by ewired** [VSCodeVim/Vim#3329]
**Describe the bug**
```
Unhandled rejection. Promise [object Promise]. Reason: Failed to execute git {
  "exitCode": 1,
  "gitCommand": "config",
  "stdout": "",
  "stderr": ""
}.
```

**To Reproduce**

1.  Start VSCode
2. See error

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/37567272/50724703-50abb280-10b7-11e9-8e10-4222970183df.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.0
- VSCode version: 1.30.0
- OS: Ubuntu (via Snap Store)

**Additional context**

Does not occur on previous version of VSCodeVim.

**Comment by jpoon** [comment]
To provide context on why you are now seeing this error, is that with v1.0.0, we've decided to show vim extension errors as these alerts so that it would be easier for users to identify errors when vscodevim is misconfigured (ie. remappings, neovim) or when things are not working as expected. We've always logged it to the console, but this wasn't very discoverable. The related configurations are below if you would like to go back to the old behaviour of living in bliss/ignorance of these errors 😅 :

Setting | Description | Type | Default Value
-- | -- | -- | --
vim.debug.suppress | Boolean indicating whether log messages will be suppressed. | Boolean | false
vim.debug.loggingLevelForConsole | Maximum level of messages to log to console. Logs are visible in the developer tools. Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error
vim.debug.loggingLevelForAlert | Maximum level of messages to present as VS Code information window.  Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error

----

In terms of your error, no idea where that is coming from. How can I reproduce this?
