### ISSUE TITLE
historyFile: Failed to create directory. path=/home/user/.cache/VSCodeVim. err=true.

### ISSUE THREAD

**Issue by ewired** [VSCodeVim/Vim#3330]
**Describe the bug**

(when doing `:e` command; for `:w`, this does not show up)
```
commandLine: Error executing cmd=e ~/.bashrc. err=true.
```

(these notifications show up for any ex command)
```
Unhandled rejection. Promise [object Promise]. Reason: true.
```

```
historyFile: Failed to create directory. path=/home/(my username)/.cache/VSCodeVim. err=true.
```

**To Reproduce**

1. Open text file
2. Do `:w` or `:e ~/.bashrc`, seems to be any ex-mode command
3. See errors

**Expected behavior**
Ex commands behave as intended with no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/37567272/50724811-e267ef80-10b8-11e9-982f-7cd4c94280e4.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.0
- VSCode version: 1.30.0
- OS: Ubuntu (via Snap Store)

**Additional context**

Does not occur on previous version of VSCodeVim.

These errors do not occur if the directory is not present. It is re-created by attempting the bug. Attempting the bug while the directory exists results in the errors. The directory contains the file `.cmdline_history`. The file does not grow in size when attempting the bug.

**Comment by jpoon** [comment]
To provide context on why you are now seeing this error, is that with v1.0.0, we've decided to show vim extension errors as these alerts so that it would be easier for users to identify errors when vscodevim is misconfigured (ie. remappings, neovim) or when things are not working as expected. We've always logged it to the console, but this wasn't very discoverable. The related configurations are below if you would like to go back to the old behaviour of living in bliss/ignorance of these errors 😅 :

Setting | Description | Type | Default Value
-- | -- | -- | --
vim.debug.suppress | Boolean indicating whether log messages will be suppressed. | Boolean | false
vim.debug.loggingLevelForConsole | Maximum level of messages to log to console. Logs are visible in the developer tools. Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error
vim.debug.loggingLevelForAlert | Maximum level of messages to present as VS Code information window.  Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error

----

Interesting. The logic seems ok for checking if the directory exists https://github.com/VSCodeVim/Vim/blob/d771023ccc663e0ee676a00aa40c75bf2e10d566/src/history/historyFile.ts#L64. Don't see this on Windows.

**Comment by doubledjdcb** [comment]
I had the same problem on mac mojave.  I'm horrible at node but it might be an issue with `fs.exists`.  I changed that function and it works 
`if (!(yield util.promisify(fs.existsSync)(this._historyDir))) {`

**Comment by jpoon** [comment]
I wasn't able to reproduce this issue but I'm hpoing https://github.com/VSCodeVim/Vim/pull/3337 fixes it. Please reopen if that's not the case.
