### ISSUE TITLE
Occurs when I save and quit.

### ISSUE THREAD

**Issue by Hoastar** [VSCodeVim/Vim#3331]
**Describe the bug**

ModeHandler: error handling key=
. err=TypeError: Cannot read property 'document' of undefined.

**To Reproduce**

1. ":wq"  save and quit

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:  v1.0.0
- VSCode version:  1.30.1  x64
- OS: Debian 4.9.135-1 (2018-11-11) x86_64 GNU/Linux  4.9.0-8-amd64

**Additional context**

**Comment by jpoon** [comment]
To provide context on why you are now seeing this error, is that with v1.0.0, we've decided to show vim extension errors as these alerts so that it would be easier for users to identify errors when vscodevim is misconfigured (ie. remappings, neovim) or when things are not working as expected. We've always logged it to the console, but this wasn't very discoverable. The related configurations are below if you would like to go back to the old behaviour of living in bliss/ignorance of these errors 😅 :

Setting | Description | Type | Default Value
-- | -- | -- | --
vim.debug.suppress | Boolean indicating whether log messages will be suppressed. | Boolean | false
vim.debug.loggingLevelForConsole | Maximum level of messages to log to console. Logs are visible in the developer tools. Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error
vim.debug.loggingLevelForAlert | Maximum level of messages to present as VS Code information window.  Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error

----

Can confirm. This is repro'd every time.

**Comment by Hoastar** [comment]
Oh,thanks for your reminder and answer .  I will try to make a setting
