### ISSUE TITLE
visual block mode ? (ctrl+V)

### ISSUE THREAD

**Issue by sapiens-sapide** [VSCodeVim/Vim#353]
am I missing something or there is no visual block mode (ctrl + V)

**Comment by jpoon** [comment]
To get into visual mode, it's either `v` or `V`. 

To be honest, I didn't even know `ctrl+v` (http://vimdoc.sourceforge.net/htmldoc/visual.html#CTRL-V). I can't seem to try it out either on vanilla vim on either my mac or windows as it defaults to pasting.

**Comment by johnfn** [comment]
Visual Block mode is a pretty sweet Vim feature that allows you to operate on rectangular blocks of text. I've been putting it off because it's a lesser-known feature and I thought it would be difficult (it involves multiple cursors). However, I've been thinking about it more recently, and I don't think it would be too bad! I'll probably get to doing it soon (TM).

**Comment by localvar** [comment]
@johnfn, it will be good if this can be mapped to ctrl-Q by an option. I like ctrl-v to be pasting too.

**Comment by johnfn** [comment]
Right; I don't think I can do this until I do command remapping.

**Comment by coolicer** [comment]
support visual block mode ?

**Comment by johnfn** [comment]
Closing in favor of #401.
