### ISSUE TITLE
current line scroll to top when begin editing in split editor

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#358]
occurs very often after the first occurrence, but not 100% reproducible, and sometimes it is more often in one pane than the other:

1. open a file
2. split the editor
3. scroll down the left pane
4. mouse click to switch between the 2 edit panes
5. begin edit in the left pane via `o`, `i` or `p` (and maybe other commands)

the current line scroll to the top of the pane.

**Comment by johnfn** [comment]
I've been putting this off because it's difficult to reproduce, but I do think I know why this happens.

**Comment by johnfn** [comment]
Absolutely 100% reproducible when you edit the same file twice. 

No idea why it happens! It's very strange.

**Comment by rebornix** [comment]
I'm not 100% sure now but seems it's caused by buffering. When you click `Split`, VS Code will open a new Editor Group and open the same file you opened in the left Group. So now you have two same files opened in the workspace. They share the same buffer but they don't share the same cursor position. While the inconsistent cursor position is by design because you may want to compare the file side by side, a consistent cursor position will make this impossible.

So a quick fix in my mind for now is holding cursor positions with Tab instead of buffer.
