### ISSUE TITLE
Buffer navigation

### ISSUE THREAD

**Issue by Chaiomanot** [VSCodeVim/Vim#360]
:ls and :b is missing

**Comment by johnfn** [comment]
@Chaiomanot Are you sure you need this? With the latest insider version of VSCode, we now have full-fledged tabs inside of VSC. They're all visible on the top of the screen, and you can navigate very easily between them with cmd-p.

I guess I never understood the appeal of Vim buffers over cmd-p and tabs. Feel free to persuade me otherwise, if you think they're superior, though!

**Comment by Chaiomanot** [comment]
The buffers aren't numbered with cmd-p. But it is adequate.
