### ISSUE TITLE
Regression: full path to nvim is now required

### ISSUE THREAD

**Issue by fredemmott** [VSCodeVim/Vim#3754]
**Describe the bug**

In previous versions, if `nvim` was in $PATH, entering `nvim` as the nvim path was sufficient; now the full path (e.g. `/usr/local/bin/nvim` is required)

**To Reproduce**

1. Install nvim (e..g `brew install nvim`)
2. open vscode-vim settings
3. enter `nvim` as the path
4. restart vscode
5. get error about being unable to stat `nvim`

**Expected behavior**

Neovim functionality works with `nvim` if`nvim` is in `$PATH`

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:  1.8.0
- VSCode version: 1.33.1
- OS: MacOS Mojave 10.14.4

**Comment by jpoon** [comment]
Feel free to fix, it's either here:

https://github.com/VSCodeVim/Vim/blob/4a79e3c1dd08b4a0c387dc1cc8b071490044fa71/src/configuration/validators/neovimValidator.ts#L12

and/or

https://github.com/VSCodeVim/Vim/blob/b2899bdfd916fd6f8eaa203005462e25df6a0e42/src/neovim/neovim.ts#L88

**Comment by neobats** [comment]
I'm trying to reproduce this to (hopefully) make and submit a fix. Trying to recreate this on a Windows machine, however, so admittedly, things will be different. The error I'm encountering at the moment is that the default path is the same location as `$MYPROFILE/AppData/Local/Programs/Microsoft VS Code`, rather than the path to nvim itself. Was hoping someone might be willing to help me make sure I'm approaching this correctly. Am I setting the path location correctly when I type `C:/tools/neovim/Neovim/bin`? I've tried with just `/neovim` and `/neovim/Neovim` as well.
I haven't been able to verify that neovim has been added to my path, though neovim says it has.

**Comment by fredemmott** [comment]
it should check every location in the `PATH` environment variable

For example, if `PATH=/usr/local/bin:/usr/bin:/bin` (e.g. Linux and Mac) , it should accept any out of `/usr/local/bin/nvim`, `/usr/bin/nvim`, or `/bin/nvim`

On windows, I think it's basically the same principle, but `Path` instead of `PATH` and separated with `;` instead of `:`.

Based on `$MYPROFILE/AppData/Local/Programs/Microsoft VS Code` it sounds like you're looking at working directory or vscode paths instead of the system Path variable

**Comment by fredemmott** [comment]
Instead of directly dealing with the system variable, an alternative would be to try executing it without a stat and catch failures
