### ISSUE TITLE
Exit from Visual-Line mode moves cursor

### ISSUE THREAD

**Issue by pattersongp** [VSCodeVim/Vim#3975]
**Describe the bug**
When you enter visual-line mode, then immediately exit, your cursor is taken to the end of the line.

**To Reproduce**

1. Enter visual line mode, eg shift+v
2.  Escape
3. Observe

**Expected behavior**
The cursor should not move at all

**Environment**
- Extension (VsCodeVim) version: v1.9.0
- VSCode version: 1.36.1
- OS: macos x 10.14.5

**Comment by caleywoods** [comment]
I'd like to take a stab at this one @J-Fields  - any details to offer on where a good starting point in the code would be? What handles entering visual line selection mode when the user enters `shift + v`?

Is [this](https://github.com/VSCodeVim/Vim/blob/38c268a26dadbd0fed1ea297923e7640f358097c/src/mode/modeHandler.ts#L112) involved? Sounds like a fun time :D

**Comment by J-Fields** [comment]
@caleywoods It seems like [this](https://github.com/VSCodeVim/Vim/blob/master/src%2Fmode%2FmodeHandler.ts#L1219) is where we create the selection and [this](
https://github.com/VSCodeVim/Vim/blob/master/src%2Fmode%2FmodeHandler.ts#L610) is where we set the cursor position after going back to normal mode

**Comment by caleywoods** [comment]
I think I've got a solution for this but I'm having a hard time running the existing test suite. Removing `.vscode-test` and then executing `gulp test` does all of the docker magic but then it just seems to exit (with code 0) successfully without any of the test output I remember from before.

I edited the dockerfile to remove the entrypoint and ran it again, then went into a bash prompt on the container and manually tried `npm test` and they do the exact same thing. 

[Screenshot](https://i.imgur.com/Z03sv5G.png)

**Comment by caleywoods** [comment]
Confirming that it would be expected for some of the visual line selection tests written prior to this fix would now fail such as `gq handles spaces after single comments correctly`. The old test expects the cursors end position to be on line 1 (the newly created line from the wrap). Post-fix, however, the cursor will reside on line 0 (the original line) since the cursor now maintains the position that it started at instead of moving elsewhere. 

[Current test](https://github.com/VSCodeVim/Vim/blob/master/test/mode/modeNormal.test.ts#L1334)

I'm thinking the new test would be:
```
  newTest({
    title: 'gq handles spaces after single line comments correctly',
    start: [
      '//    We choose to write a vim extension, not because it is easy, but because it is hard|.',
    ],
    keysPressed: 'Vgq',
    end: [
      '//    We choose to write a vim extension, not because it is easy, but because it i|s',
      '//    hard.',
    ],
  });
```

The cursor remains on the same line as it started and one character before the end of the line. The test does pass when modified this way, I just wanted to do a sanity check on it.

**Comment by J-Fields** [comment]
Actually, after playing around with this a bit, it seems Vim only preserves the column when you exit via `<Esc>`. If you do a real action, it adjusts the position.

**Comment by caleywoods** [comment]
> Actually, after playing around with this a bit, it seems Vim only preserves the column when you exit via `<Esc>`. If you do a real action, it adjusts the position. So this test shouldn't change.

That sounds like in addition to tracking the original cursor position when entering visual line, when they drop back to normal mode I need to check the last two elements in `vimState.keyHistory` to make sure they were `V` and `<Esc>`, any other key at position "-2" (second to last) would indicate the user made a linewise movement.

Something like this:
```
const immediatelyExited = vimState.keyHistory.slice(-2) === ['V', '<Esc>'];
// if ^ this bool is true we set cursorStopPos to the original start position before visual line mode
```

So, `Vjj<Esc>` we would not adjust cursor position but `V<Esc>` we would. Are there i18n concerns here or concerns about users having keybinds that exit visual line selection that would make this fail? I know in insert mode I exit with `jj` but I logged out `keyHistory` and it looks like that does still send `<Esc>` (as I was expecting since you create the bind to do that).
