### ISSUE TITLE
`d2}` deletes only one paragraph.

### ISSUE THREAD

**Issue by toriwasa** [VSCodeVim/Vim#4488]
**Describe the bug**

`d2}` deletes only one paragraph.

**To Reproduce**

1.  Write a multi-paragraph document.
2.  Move the cursor to the beginning of the first line.
3.  Enter `d2}` in normal mode.
4.  Only one paragraph will be deleted.

Example:

```
|aaa
aaa

bbb
bbb
```

then Enter  `d2}`

```
|
bbb
bbb
```

**Expected behavior**
`d2}` deletes two paragraphs.

**Screenshots**
![screenshots_gif](https://user-images.githubusercontent.com/27913937/72205145-1beceb00-34c3-11ea-9f4e-91c023dbf80d.gif)

`d2}` deletes only one paragraph.
`d2{` deletes two paragraphs.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1(user setup)
- OS: Windows 10 Ver1903 build 18362.535

**Additional context**

`y2}` and `c2}` also edit only one paragraph.
`d3}` deletes two paragraphs.
`d4}` deletes two paragraphs.
`d5}` deletes three paragraphs.

**Comment by J-Fields** [comment]
Same for `2d}`.

**Comment by cvaldev** [comment]
I looked into this and I found that doing `d2}` not at the beginning of line works as expected, sort of. I say 'sort of' because the extension doesn't respect the cursor position and deletes the whole entire line, which is not what regular Vim does. The source of the issue appears to be from the `}` move, I think I have a solution for it.
