### ISSUE TITLE
Default vscode extensions are not working at all.

### ISSUE THREAD

**Issue by twistapp** [VSCodeVim/Vim#4490]
**Describe the bug**

I have been using vscode with the vim extension for the last year in my OSX, and now that I switched to Linux, the original bindings of vscode don't work when the vim extension is enabled. Is this a bug? Is it possible to preserve the visual studio code bindings while using the vim extension? Am I missing some configuration?

**To Reproduce**

Not sure how, I've just installed the extension.

**Expected behavior**

The default vscode bindings should work regardless of having or not having the vim extension enabled.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.41.1
- OS: Linux

**Comment by ElvenSpellmaker** [comment]
Do you mean keybindings? It seems the extension adds loads of its own custom ones.

I've had to go through and remove a lot of them, because it's completely unintuitive as it comes out of the box.

![image](https://user-images.githubusercontent.com/2286713/72211162-7d5e8b00-34be-11ea-82b1-ce872845049b.png)

An example of some of the overrides that come by default ^

**Comment by J-Fields** [comment]
`vim.useCtrlKeys` lets you give keybindings back to VSCode. This is generally the preferred solution to @ElvenSpellmaker's approach, though it's not 100% flexible. One improvement I think we should make at some point is to allow a different set of keys per mode.
