### ISSUE TITLE
Easymotion - Gray out fonts when activated 

### ISSUE THREAD

**Issue by fourcolors** [VSCodeVim/Vim#4524]
**Is your feature request related to a problem? Please describe.**
I'd like greater focus when jumping to words in EasyMotion

**Describe the solution you'd like**
VIM Easymotion will gray out the code text when you activate it. It would be nice to have this option as well https://github.com/easymotion/vim-easymotion

**Comment by MathiasKandelborg** [comment]
If you want to see easymotion clearer, I'd suggest to use the options for changing the background and text color. 

I'm pretty sure this is a very heavy task, if it's default please don't make it default. There's no reason to create such a intensive default when most people easily can distinguish between colors...

I have been trying to do some things with vscode on arch (save as sudo, transparency) and I just realized that me missing highlighting probably is attributed to this exact default setting that doesn't really have anything to do with easymotion or vim, but people having a hard time distinguishing colors.

I had to go through the change-log and luckily find this issue. There's no mention of this setting anywhere, which by the nature of it (unload all colors, then, when done, load all colors again in the correct places) should be more 'accessible' and mention how intensive the task is.


I'm done talking reasonable choices and defaults as well as efficiency now. I'd like to mention that it probably is a bug somewhere (not in easymotion/vim) that resulted in no highlighting for me. I hadn't used the extension and on some builds the extensions simply aren't there. 

But my guess is that the `vim.easymotionDimBackground` has effects how vscode want to intruct the editor in coloring grammar, and if there's this setting has been triggered (by installing the extension) it might change some other default setting that messes up vscode's instructions

**Comment by berknam** [comment]
Just so you now the background dimming uses the vscode `TextEditorDecorationType` that simply adds a css class with the css styles you want to the range of code that you want. There is no change of settings, or highlighting at all. This decorations only show when the extension uses the command to show them and as soon as you restart vscode they will be gone (if an extension needs to use one of this decorations it needs to set it every time when loading). So when you disable or remove an extension it is impossible for one of this decorations to linger around.

Since this change is only a css change it isn't a heavy or intensive task. Vscode and a lot of other extensions use this all the time. The code lenses are made like this, the little lamp bulb you see when there are code actions available is made like this.

Your issue is probably something else and is not related to this easymotion setting at all. It's probably not even related to Vim extension because this extension doesn't mess with any sort of Highlighting user settings. It only creates two new types of highlight for the search highlight and yank highlight.
