### ISSUE TITLE
Cursor position after surround in visual mode is wrong

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#4869]

**Comment by TransientError** [comment]
I've noticed recently when I use surround in visual mode, the cursor ends up near the end of the selection instead of on the beginning of what was inserted e.g. from the tests
starting from 
```first li|ne test```
and pressing `viwS)`
ends up with
```first (lin|e) test```
But vim-surround would actually end up with
```first |(line) test```

I hope this is the right issue for discussing this bug.

I dug into it a little (since I was worried this was caused by me) and noticed if I change [this line](https://github.com/VSCodeVim/Vim/blob/0a5093f4b1da61b66473db61af353f453927d1a4/src/actions/plugins/surround.ts#L249) to start instead of end, I get the desired experience. I was hoping you could provide some insight about why it was set to end.

When I [added the PositionDiff](https://github.com/VSCodeVim/Vim/blob/0a5093f4b1da61b66473db61af353f453927d1a4/src/actions/plugins/surround.ts#L468) for the `ysiw)` case, I was expecting the cursor to be at the start of the range.

I've run the tests, and I don't notice any other regression, so if this was a mistake I'd be happy to make a PR for it.

Also worth noting is that this doesn't fix the visual line case.

**Comment by J-Fields** [comment]
Thanks for looking into this @TransientError!

This was caused by me a while back - I forget what the change was tbh. I'd planned on fixing it soon after filing this issue, but never got around to it. If you wouldn't mind, a PR would be greatly appreciated!
