### ISSUE TITLE
no working ctrl + c and ctrl + v

### ISSUE THREAD

**Issue by Gercog52** [VSCodeVim/Vim#4953]
**Describe the bug**

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by DimmyJing** [comment]
This is intended behavior as vim maps ctrl-c and ctrl-v to something else too. You can either use vim copy and paste through the + register (`"+y` and `"+p`) if you want to copy or paste from system clipboard. Otherwise, you can just copy and paste how you would do it in vim.

You can also remap ctrl-c and ctrl-v to copy and paste through settings.json, but I'm not completely sure what those settings would look like.

**Comment by berknam** [comment]
When you are in InsertMode `<C-v>` should paste like per usual but in normal our visual modes it changes to VisualBlockMode.

You can also set those keys to be handled by VSCode instead of VSCodeVim by doing:
```
"vim.handleKeys": {
    "<C-c>": false,
    "<C-v>": false
},
```
But if you do this then you can't get into Visual Block Mode with `<C-v>`.

**Comment by Gercog52** [comment]
thank very much, this works)))
