### ISSUE TITLE
bug: Exit MULTI CURSOR when accessing through NORMAL MODE

### ISSUE THREAD

**Issue by ofrades** [VSCodeVim/Vim#5002]
**Describe the bug**
When I am at --NORMAL-- and go to --INSERT-- MULTI CURSOR, ESC does not get me out back to --NORMAL--.
Instead goes to --NORMAL--MULTI CURSOR and the only way I found to put me out of MULTI CURSOR is to go to --VISUAL BLOCK-- MULTI CURSOR and from there I can go to --INSERT--MULTI CURSOR and ESC works properly putting me back to --NORMAL--

**Comment by J-Fields** [comment]
Hmm, hitting escape should get you out of multicursor mode from normal mode

**Comment by ofrades** [comment]
It works fine if you go to multicursor from Visual Block, but if you go from Normal does not.

**Comment by ofrades** [comment]
![multicursor](https://user-images.githubusercontent.com/31070771/86949094-1278ce80-c146-11ea-87c9-34335bb29b66.gif)

**Comment by J-Fields** [comment]
Hmm, weird. What platform are you on, and could you post your settings?

**Comment by ofrades** [comment]
Sure:
VS Code version: Code - Insiders 1.47.0-insider (b16b467d3e03e1a1ae05b5836e4e5a5af504e86d, 2020-07-01T05:32:07.483Z)
OS version: Windows_NT x64 10.0.18363

**Comment by berknam** [comment]
When you are on "Insert Multicursor" mode, if you press escape you are supposed to go to "Normal Mutlicursor" mode and then if you press escape again you go to "Normal" mode.

This AFAIK is by design!

The reason it goes straight to Normal mode after you use VisualBlock is because when in visual block if you go into insert mode VSCodeVim makes use of the multicursors so that you can see your insertions being applied on all cursors, it is considered a fake multicursor that is used just to make the insertions and then go back to normal mode. That is what is happening to you. When you're going to insert mode after VisualBlock VSCodeVim is creating the multicursors (even though they already existed) and then since it now considers these to be fake multicursors used only for the visual block insertions it lets you go straight to Normal mode.
This for me could maybe be considered the bug here.

But the normal behavior is:
 - Enter Normal Multicursor mode
 - Go to Insert Multicursor mode and make your changes
 - Press escape to go back to Normal Multicursor mode
 - Press escape again to go back to Normal mode (no multicursor) **(Is this second escape not working for you? If so, that then is a bug!)**

**Comment by ofrades** [comment]
Yes the second escape is not working, like I said, I am unable to leave the multicursor if I do that. The only way is to go to visual block and from there to insert multicursor and from there to normal multicursor and only after that escape works.

**Comment by berknam** [comment]
How are you entering to multicursor mode? Can you gives more info so we can try to reproduce that, your settings and/or installed extensions? Because I can't reproduce that.

**Comment by ofrades** [comment]
In normal mode I run the editor.action.selectHighlights, after that I go to insert mode with multicursor.
```
    {
      "before": ["leader", "m"],
      "commands": ["editor.action.selectHighlights"]
    }
```

**Comment by J-Fields** [comment]
That works fine for me. My intuition is that `VimState.isMultiCursor` is getting out of sync with the number of cursors somehow. If that's the case, it should be fixed by my multicursor test harness branch - I've been meaning to get to back to that...

**Comment by ofrades** [comment]
Is fixed now, thanks!!
