### ISSUE TITLE
Ex command 'put' is not working properly

### ISSUE THREAD

**Issue by tctco** [VSCodeVim/Vim#5052]
**Describe the bug**
`:put` command seems not working properly?

**To Reproduce**
1. `:.put=join(range(5), ' & ')`
2. There will be an error `E488: Trailing characters`

**Expected behavior**
Should put "0 & 1 & 2 & 3 & 4"

- Extension (VsCodeVim) version: 1.15.0
- VSCode version: 1.47
- OS: Windows10

**Additional context**
I'm not very familiar with vim and vscode. I've tried the command with a normal vim editor and it works. I'm not sure if this is a configuration error or a bug.

**Comment by tagniam** [comment]
Hey @tctco, could you try enabling Neovim integration? Unfortunately `join()` and `range()` are Vimscript expressions, which aren't currently supported in the ex command emulation (and may never be due to the massive scope of porting all of Vimscript over to VSCode). However, if you enable Neovim integration, this should work.

**Comment by tctco** [comment]
Hi @tagniam, I've tried enabling Neovim integration but it's still not working. I'm not sure what's going wrong so I tried the neo vim extension and it works well. The extensions have similar configurations I guess? Hope I'm not missing anything...

Thank you anyway :)

**Comment by tagniam** [comment]
Ah, I see, we just haven't enabled the put command for Neovim capability. This should be an easy fix. Thank you for catching that :)
