### ISSUE TITLE
Bug (Master): Mapping + Operator + jump to non existing mark screws up vscodevim

### ISSUE THREAD

**Issue by sql-koala** [VSCodeVim/Vim#5057]
**Describe the bug**
Using an operator (d'x) with a jump to a non existing mark screws up vscodevim, because textinput changes to the command line.
Just a jump is no problem. It gives an error message and you can continue.

It is probably connected to the remapper in combination with a failing motion.

See screenshot for the problem:

**To Reproduce**

-1. Build from master
0. have a mapping like `nnoremap dw daw`
1.  open a document
2.  do: d'x
3.  See expected error message
4.  but text focus will change to command line and vim is unuseable (restart required)

Can you repro?

Another way to provoke the error, do: dg? in step 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/30384885/87983421-a056a100-cad8-11ea-96a7-da8074424684.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: master
- VSCode version: 1.47.2
- OS: windows 7 64

**Comment by berknam** [comment]
I've noticed this bug a lot of times already when doing the remapper refactor. It is not the text input that changes to the command line, that is just the 'showCmd' you're seeing. The thing is it gets stuck continuously waiting for another key. Also this only happens with operators that you have remaps that start with that operator key.

I've found a workaround so that you don't have to restart vscode, just select something with your mouse (or double click) and then press `<Esc>` twice and it should get back to a working state.

I didn't create an issue for this yet because this is fixed with my remapper refactor. So I guess this is another issue to put on the list! 😄

**Comment by sql-koala** [comment]
Ah, ok. Thanks for the detailed explanation @berknam .

**Comment by berknam** [comment]
You can keep this open until the PR gets merged. Because I'm sure there are others facing this issue as well and if they come here they don't have to create a new issue and they can see the workaround (so they are not restarting vscode every time).
