### ISSUE TITLE
Neovim mode dosen't work?

### ISSUE THREAD

**Issue by silverscat-3** [VSCodeVim/Vim#5087]
**Describe the bug**
I am using this plugin for the purpose of embedding NeoVim in VSCode, but I have recently noticed that some features of NeoVim are not working properly.
For example, the clipboard integration and key aliases are not working correctly.

**To Reproduce**
1.  Install Vim plugin
2.  Enable Neovim and setting correctly Neovim Path
3.  Restart VSCode

**Expected behavior**
The settings in the init.vim were reflected.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47.3
- OS: Arch Linux

**Additional context**

**Comment by berknam** [comment]
The Neovim integration on this extension is only used for ex commands. It is intended to allow the use of some ex commands that haven't been implemented on this extension yet like `:normal`, `:execute`, `:g` among others.

There is also the .vimrc support that is currently only used to read remaps.

Any settings you want to change to better mimic your neovim experience need to be changed through this extension settings. (Check the [README](https://github.com/VSCodeVim/Vim/blob/master/README.md) file to know what settings can be changed and check the [ROADMAP](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md) file to know which commands are already implemented.)

If there is anything you were trying to do and can't do with this extension because of a bug or a feature you would like that isn't implemented yet, then you can create an issue for that bug/feature request.

**Comment by silverscat-3** [comment]
I see. I hope to use full Neovim features at some time.

Thanks.

**Comment by berknam** [comment]
BTW what Neovim features were you trying to use that are not currently implemented on this extension?

**Comment by J-Fields** [comment]
@silverscat-3 You might be interested in this project: https://github.com/asvetliakov/vscode-neovim

I haven't used it myself, but I've heard good things

**Comment by silverscat-3** [comment]
@berknam I just want to come and go terminal to VSCode seamless. Same settings, same operation.

**Comment by silverscat-3** [comment]
@J-Fields Thank you to the information. I'll try that extension.
