### ISSUE TITLE
Easymotion motions should be considered jumps

### ISSUE THREAD

**Issue by berknam** [VSCodeVim/Vim#5111]
**Is your feature request related to a problem? Please describe.**
Currently Easymotion motions can't be traveled with jump keys `<C-o>` and `<C-i>` but the actual Vim plugin has its motions behave as jumps.

**Describe the solution you'd like**
Easymotion motions to behave as jumps.

**Describe alternatives you've considered**
None.

**Additional context**
I haven't looked into the Jump logic yet so I don't know if this is easy to do or even possible.

**Comment by J-Fields** [comment]
It certainly should be possible. Normally you'd just put `isJump = true;` on the command and call it a day. Easymotion is pretty janky though, so there's a chance it's a bit more complicated

**Comment by grozan** [comment]
I also have that problem, which defeats the whole point of easymotion for me.

My typical use-case for easymotion is "from positionA quickly jump somewhere (positionB), do something or copy something, and come back to where you were (positionA)"

Problem is the "come back to where you were" part does not work today
- the standard `workbench.action.navigateBack` command does not work. It brings the cursor back to my initial position (positionA), which looks good at first, but as soon as I start moving (one `l` press for example) then it jumps back to positionB   and does my movement relative to positionB, instead of positionA
- I also tried using extensions like Bookmarks. I save a bookmark before jumping (positionA), jump to positionB with easymotion, then use Bookmarks to bring me back to positionA. I still observe the cursor jumping back to positionB as soon as I start moving

Do I understand it correctly that if the easymotion jumps were recorded in the jump list, then I could be at positionA, initiate a jump to positionB with easymotion, do what I have to do at positionB, and then hit `C-i` or `C-o` to jump back to positiionA **and stay there**? (meaning if I move one character to the right, for example, this movement would be relative to positionA - like I would expect)

If so can you please consider implementing this asap, especially if it's a simple code change?
Thanks in advance

**Comment by berknam** [comment]
> 
> Problem is the "come back to where you were" part does not work today
> 
>     * the standard `workbench.action.navigateBack` command does not work. It brings the cursor back to my initial position (positionA), which looks good at first, but as soon as I start moving (one `l` press for example) then it jumps back to positionB   and does my movement relative to positionB, instead of positionA

This is a different issue. The `workbench.action.navigateBack` does work. It is not working for you probably because of the issue #5221 or #5268. If you try reloading the window or restarting vscode you'll see that the navigate back command will work after an easymotion.

**Comment by rndware** [comment]
I fixed this issue with the following PR #5731 seems to work like charm.
