### ISSUE TITLE
Operator pending mode binding from readme doesn't work

### ISSUE THREAD

**Issue by ejolly** [VSCodeVim/Vim#5134]
**Describe the bug**
I'm trying to implement the following binding from the README:

> Bind L to $ and H to ^ in operator pending mode makes yL and dH work like yL and d^ respectively.
    "vim.operatorPendingModeKeyBindings": [
        {
            "before": ["L"],
            "after": ["$"]
        },
        {
            "before": ["H"],
            "after": ["^"]
        }
    ]

I've also added the same mapping to normalModeKeyBindings. Moving the beginning and end of the line work just fine, but deleting or copying don't. Instead they utilize the default values of H and L (i.e. higher, lower of screen). Additionally, the operatorPendingModeKeyBindings doesn't seem to be a setting picked up by vscode at all. Is there a work around to enable this kind of behavior?

**To Reproduce**

Copy and paste example in README into settings.json

**Expected behavior**

Deleting and yanking should respect H and L bindings. 

**Environment (please complete the following information):**

Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z (5 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

VimVscode: 1.16.0

**Comment by J-Fields** [comment]
Sorry, the README is a bit ahead of the code 🙃 this feature will be in the next release, out sometime this week

**Comment by ejolly** [comment]
@J-Fields Just curious if there was any update on this release? Thanks!

**Comment by vtvh** [comment]
Looking forward for the next update on operatorPendingModeKeyBindings 🤩

**Comment by J-Fields** [comment]
> @J-Fields Just curious if there was any update on this release? Thanks!

Sorry, I've been very busy recently. I meant to get the release out a few weeks ago but realized some bugs were introduced since the last release, and I'd like to squash those and get to a stable place before that happens.

I realize that there have been some highly anticipated features & fixes since the last release, though, so I'm working on creating a beta release process so that anyone eagerly waiting can choose to accept a few bugs in exchange for those enhancements until a stable release is ready.
