### ISSUE TITLE
Operation with multi-cursor doesn't work properly

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#5208]
**Describe the bug**
Whenever there's multi-cursor involved, the following operation on multiple targets behaves weirdly...

**To Reproduce**

1.  Yank something using `yiw`
2.  Select multiple occurrences using `<C-d>` or `gb`
3.  Paste it using `p`
4.  Only the first occurrence was pasted, the rest of the occurrences were left untouched

**Expected behavior**
All occurrences are replaced by the pasted item

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS: Win10 / MacOS High Sierra

**Additional context**
If I don't use yank and paste. Instead, I just use the normal ctrl c + ctrl v, then the multi-cursor are behaving properly. Just wondering how would people do operations like this in a Vim-ninja fashion considering multi-cursor may not be a thing in native Vim.

**Comment by berknam** [comment]
@sql-koala Is this related to your issue #4562?

**Comment by sql-koala** [comment]
I had looked into this a bit ;-)
The problem is the "switch" from yanking with one cursor and then pasting with multicursor.

When I try to repro with 1.17.1 or master I get a different problem:
```
TypeError: Failed to handle key=p. Cannot read property 'split' of undefined
```

The internal "cause" is somewhere, where paste p is decomposed to (internal) yank + delete + paste operations (for each cursor). I suspect in the yank part, but I have no fix. Just a workaround:
`vnoremap P "_dP`
