### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by cj0687** [VSCodeVim/Vim#5237]
The first button of mapping, for example, my mapped ESC starts from JJ, but every time I use JJ, the cursor of the first j will move forward one bit, which is a bit troublesome in HTML

**Comment by berknam** [comment]
Can you explained better what is the issue you're facing?

The cursor behavior when pressing a key that is the start of a possible remap changed to be the same as in normal Vim. Right now if you have `jj` mapped to `<Esc>` after pressing the first `j` you should have a "virtual" `j` appearing on top of the current character and if you then press another `j` it will go to normal mode, but if you wait the `timeout` that `j` will be actually inserted.

**Comment by cj0687** [comment]
When I set the mapping, the cursor of the key I mapped, such as J, will appear in the front by mistake and wait for a second. But when I want to input a string, it will always replace the left double quotation mark with J
![)220~8GRP%XN{(W(R5HM8RJ](https://user-images.githubusercontent.com/45863730/94336935-49f66900-0019-11eb-9843-5a96c08b3790.png)

**Comment by berknam** [comment]
I'm still not understanding your issue.

Like I said, if you have `jj` mapped to `<Esc>` in insert mode then when you press the 'j' it overlaps the following character with a 'j' temporarily (for the length of 'timeout' which is 1 second by default), after that timeout finishes it inserts the 'j'. This is only a visual indication that the key you just pressed has a potential remap. (this is useful because if you actually want two input 2 'j's then that visual indication remembers you that you have to wait 1s after the first 'j' otherwise you will escape to normal mode)

For example, if you have the following situation in insert mode:

`("te|st")` ( `|` is the cursor)

If you press 'j' you get this:
`("te|jt")` ( `|` is the cursor)

Now you have two options, with the following corresponding results:

**Option 1.** Wait for timeout to end (1 second):
`("tej|st")` ( `|` is the cursor)
The 'j' is inserted and the cursor moves forward.

**Option 2.** Press 'j' again to escape (because of the remap of `jj -> <Esc>`):
`("t|est")` ( `|` is the cursor)
You get back to normal mode.

If this is what you are experiencing, then this is normal behavior. If not then maybe try to make video or a gif showing your issue.

**Comment by cj0687** [comment]
I know that's normal, but it's in English
If the string is Chinese, it can't detect as well as 1.16.0
If I want to enter console,log("我是你的骄傲"), in the case of 1.17.1, the result after input is as follows console.log("我是你j骄傲"), it will replace "的" with "j"

**Comment by berknam** [comment]
Can you explain to me the exact steps to reproduce that? When you press 'jj' quickly does it go to normal mode and leave that 'j'?
I can't reproduce that, please tell me the exacts steps. Do you use any program with imselect to input the Chinese characters?

**Comment by cj0687** [comment]
![1](https://user-images.githubusercontent.com/45863730/94362348-3ae0eb00-00ed-11eb-966b-3329a72e1d40.gif)
In this GIF, I only enter a "J"

**Comment by berknam** [comment]
What is the input method you use? Do you use any program?

**Comment by cj0687** [comment]
I just used Microsoft's input method

**Comment by berknam** [comment]
I've created the PR #5271 which should fix this. If you can test it out and give me some feedback.

**Comment by berknam** [comment]
@cj0687 Thank you for your help troubleshooting this!
