### ISSUE TITLE
Snippet is not working Properly 

### ISSUE THREAD

**Issue by grim-firefly** [VSCodeVim/Vim#5240]
when i write a for loop using snipet's . when i press TAB key it's auto come to normal mode. 
![Screenshot from 2020-09-25 00-05-41](https://user-images.githubusercontent.com/56791251/94182477-e3f7cd80-fec2-11ea-8106-f92efc7da578.png)

**Comment by JW9506** [comment]
If you are using the latest 1.17 and seeing the bug, just downgrade to 1.16 manually

**Comment by grim-firefly** [comment]
thanks a lot. i downgrade to 1.16.0 and it's worked perfectly :100: 

> If you are using the latest 1.17 and seeing the bug, just downgrade to 1.16 manually

**Comment by draivin** [comment]
I'm hitting a similar issue with my extension `hsnips`, though it only happens when vscode's `insertSnippet` is called directly. You can see the related issue here https://github.com/draivin/hsnips/issues/28.

**Comment by draivin** [comment]
I just did a `git bisect`, which reveals that in my case this commit is the culprit: https://github.com/VSCodeVim/Vim/commit/35d06e6780fbde4624081e47ddfc95cd60a1451d.

**Comment by berknam** [comment]
Whats happening here is that we've made a change that when we get a selection we go into visual mode (which is what happens in normal Vim).

When using snippets it creates a selection which goes into visual mode. Which shouldn't be any issue, one could just press `c` to change the current selected word(s) deleting that word(s) and going into insert mode and then write the new word(s) we want and press \<Tab\> to go to the next snippet placeholder. Now this here is the problem! We can't handle the \<Tab\> key (like explained on #5131) so there is no way of us knowing that the user pressed TAB to go to the next placeholder, so from VSCodeVim point of view the user is still in insert mode after pressing the operator `c`, and after they press \<Tab\> it goes to the next placeholder and it creates a selection again which changes mode to visual, but VSCodeVim still thinks it is in the middle of a ChangeOperator so then it doesn't do anything if you try to press 'c' again, you would have to press it twice in order to work.

Since we probably won't be able to fix the issue with TAB any time soon, I'm trying to find a way to detect a selection as being from a snippet so that we don't go into visual mode.

@J-Fields I'm working on this one, but any ideas are welcome.

**Comment by breemts** [comment]
Something similar for me. When I do ctrl+f to search for something with 'VSCode search' in insert mode it still is in insert mode. But when I select find next and previous I'm back into normal mode. 
This also seems to stack up. So when searching back and forth I have to press 'i' multiple times to get back into insert mode.

I have set "vim.useCtrlKeys": false,

**Comment by berknam** [comment]
> 
> 
> Something similar for me. When I do ctrl+f to search for something with 'VSCode search' in insert mode it still is in insert mode. But when I select find next and previous I'm back into normal mode.
> This also seems to stack up. So when searching back and forth I have to press 'i' multiple times to get back into insert mode.
> 
> I have set "vim.useCtrlKeys": false,

The is a different thing. When you do a search vscode selects the word. Recently a change was made that every time vscode creates a selection we go to visual mode. This is the same behavior as in normal Vim, except in normal Vim you can change it to go to SelectMode instead of VisualMode. Since select mode hasn't been implemented yet we go to visual mode, then you do as expected in visual mode, want to change the selected word press 'c', want to append to that selection press 'A', want to copy press 'y', want to delete press 'd', etc.

**Comment by jganetsk** [comment]
> I'm trying to find a way to detect a selection as being from a snippet so that we don't go into visual mode.

Is there a `jumpToNextSnippetPlaceholder` event type?

**Comment by berknam** [comment]
> 
> 
> > I'm trying to find a way to detect a selection as being from a snippet so that we don't go into visual mode.
> 
> Is there a `jumpToNextSnippetPlaceholder` event type?

No. AFAIK there are no triggered events after a command being ran that the API exposes to the extensions.

I've created the PR #5540 to try and fix this, can any of you test it and post your feedback?
