### ISSUE TITLE
gd Goto Defination doesn't work

### ISSUE THREAD

**Issue by eshiva0** [VSCodeVim/Vim#5358]
Using VscodeVim 1.17.1
All of sudden gd command and "c+]" stopped working. Tried to reinstall VSCode by clearing cache from %userprofile% too. Still no luck. Please help me to get out of this issue. This is a basic need while using VIM. Without this, I stopped using VSCode momentary. Please make me to get back onto VIM again.

Even removed all other plug-ins. Otherthan VIM, don't have any other extensions installed.

Thanks in advance.

**Comment by sql-koala** [comment]
Hi, I can try to help you.
Some things to try:
* Uninstall 1.17.1. Restart Vscode, then install 1.16. Does this help?
https://github.com/VSCodeVim/Vim/releases/download/v1.16.0/vim-1.16.0.vsix
* VSCode has these commands, do they work? Menu "Go" -> Goto Declaration, Goto Definition
* what language does this happen?
* do you have vim maps that could conflict with "gd"?

**Comment by eshiva0** [comment]
Thanks for help.

I uninstalled the 1.17.1 and rested the VSCode but unable to find different version of VsCodeVIM. I am not provided with settings ICON to install the different version of it.
![image](https://user-images.githubusercontent.com/53137859/95544110-dcced480-0a17-11eb-91d7-5fed226b990a.png)

Yes.. I don't see even "Go" -> Goto Declaration, Goto Definition. I expected this was coming from C/C++ extension but now realized that it is not from this plug-in.

I using ".c" files. I did not configure any vim maps. However sometime back I added ctrl+c to work for copy by adding it in JSON but after that I removed again. Not sure whether I have messed up the file or not. For that reason, I reinstalled everything. BTW how to reset the plugins completly. 

![image](https://user-images.githubusercontent.com/53137859/95544305-5797ef80-0a18-11eb-93e0-6a6ac72fa31a.png)

**Comment by sql-koala** [comment]
Hi, ok, I think the issue is not about the vim version. You can install 1.17.1 again.

It is about "interacting" with the c/c++ extension.
I am not using it, so i am no expert there. But I think this leads to a solution. Here are the menu/commands I mentioned. Try "Goto Definition". If that is what you are looking for, then we are one step ahead.
![vscode_Goto](https://user-images.githubusercontent.com/30384885/95553092-22869f80-0a0e-11eb-8101-f82f86b7fdfa.png)

**Comment by eshiva0** [comment]
Yes.. Go" -> Goto Definition" doesn't work for me. These options used to show on right click menu context earlier. But now I don't see these options on context menu as well. Anyway even from "Go" Menu also, this is not working.

**Comment by sql-koala** [comment]
Hmm, ok, sorry then I don't know how to help you... :|

**Comment by eshiva0** [comment]
Is it works for you (gd command). In that case, I will check more on clean fresh installation part.

**Comment by JW9506** [comment]
Did you correctly configure, for example 
` "C_Cpp.default.compilerPath": "C:/msys64/mingw32/bin/g++.exe",`
`"C_Cpp.default.intelliSenseMode": "gcc-x86"`? 
VSCode apprently needs to know which compiler for the current working folder before it can provide you any intellisense.

**Comment by eshiva0** [comment]
No, I haven't configured these. Can you please let me know where to add these exactly.

**Comment by berknam** [comment]
@eshiva0 The `gd` command calls the vscode command `'editor.action.goToDeclaration'` so if the vscode 'Go to Declaration' isn't available then `gd` will do nothing. But your issue is probably not related to this extension.

If you don't have the 'Go to Declaration' try checking if you have the extension 'C/C++ `ms-vscode.cpptools`' installed and enabled. If it is, try uninstalling it and installing it again, then restart vscode or reload the window. After that open your Ouput tab (`Ctrl+Shift+U`) then on the dropdown look for `C/C++` and see if it says something like 'Finished installing dependencies' or if it has an error.

Also notice that in some languages (don't know if C is one of them or not) you don't get intellisense running after you create a new file and change the language to what you want. Sometimes it will only work after you save the file somewhere.

**Comment by eshiva0** [comment]
After  installing 'C/C++ ms-vscode.cpptools', it worked like a charm!! Not sure why it didn't work previously though I tried sometime back. Anyhow thanks very much @berknam for getting back me back onto vim..

And other observation is, I don't see C/C++ option on the dropdown list. Checked for both C and CPP projects. Initially one time I have seen it may be before installing C/C++ plugin. Now I am not seeing this. Never the less, my problem is solved. Thanks everyone who supported me.
