### ISSUE TITLE
Keymappings aren't ported.

### ISSUE THREAD

**Issue by TornaxO7** [VSCodeVim/Vim#5527]
**Describe the bug**
All keybindings don't work like `<C-Space>`.

**To Reproduce**

1. Add these to your `settings.json`:
```json
    "vim.leader": "<Space>",
    "vim.vimrc.path": "~/.config/nvim/init.vim",
    "vim.enableNeovim": true,
    "vim.changeWordIncludesWhitespace": true,
    "vim.cursorStylePerMode.insert": "line",
    "vim.cursorStylePerMode.normal": "block",
    "vim.cursorStylePerMode.replace": "underline",
    "vim.cursorStylePerMode.visual": "block",
    "vim.cursorStylePerMode.visualblock": "block",
    "vim.cursorStylePerMode.visualline": "block",
    "vim.debug.loggingLevelForAlert": "debug",
    "vim.foldfix": true,
    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<C-NULL>"
            ],
            "after": [
                "<Esc>"
            ]
        }
    ],
    "vim.debug.loggingLevelForConsole": "debug",
    "vim.handleKeys": {
        "<Space>": false,
        "<C-d>": true,
        "<C-f>": false,
        "<C-Space>": false,
        "<C-a>": true,
    },
    "vim.highlightedyank.enable": true,
    "vim.neovimPath": "/usr/bin/nvim",
    "vim.normalModeKeyBindingsNonRecursive": [],
    "vim.sneakReplacesF": true,
    "vim.useSystemClipboard": true,
    "vim.vimrc.enable": true,
```
Try to use one of your keymappings like this one:
```vim
inoremap <C-Space> <Esc>
```

**Expected behavior**
I expected that my keybindings work but none of them seems to work.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.50.1-1 (code)
- OS: Arch Linux (5.9.1-arch1-1)

**Additional context**

**Comment by berknam** [comment]
I don't know what `"<C-NULL>"` is supposed to be, but currently we don't capture Ctrl+space key combination that is why you can't map that one. But any other remaps should work. Are you using your .vimrc or actually porting your remaps to settings.json? What other remaps are not working?

**Comment by TornaxO7** [comment]
I'm using `neovim` so I've an `init.vim` file and not a `vimrc`.
This is another mapping which doesn't work:
```vim
noremap <S-j> 5gj
```
My mappings are all in my `init.vim` or let's rather say, `mapping.vim` because `init.vim` "includes" my mappings from my `mappings.vim` file. 

`"<C-NULL>"` is supposed to be `<Ctrl-Space>` but well, if it doesn't work, than I need to find another keybinding xD

**Comment by J-Fields** [comment]
> My mappings are all in my `init.vim` or let's rather say, `mapping.vim` because `init.vim` "includes" my mappings from my `mappings.vim` file.

You mean with `source`? This is not currently supported (in fact, no vimscript except `map` commands is supported).

**Comment by TornaxO7** [comment]
Well, that makes sense. Yes I mean `source`. Is really only `map` supported? So no `nnoremap`, `noremap`, `vnoremap`, etc. ?

**Comment by berknam** [comment]
All sorts of map are supported except the terminal maps like `tmap, tnoremap` and the select mode mappings revert to visual mode mappings so `smap`, `xmap` and `vmap` currently are the same. But everything else should work, even unmaps like `unmap` or `nunmap`. The short versions should work as well, `nno` is `nnoremap`, `ino` is `inoremap`, etc.

So if you copy the mappings from your 'mapping.vim' to 'init.vim' they should be captured. I have it on my list to eventually implement the `:map` commands so when can at least now what mappings are currently available, but haven't had the time yet.

Also your map `noremap <S-j> 5gj`, is it supposed to be `J` (uppercase)? If so you need to change that to `noremap J 5gj` because the `<S-*>` (where `*` is any character) isn't currently supported.

**Comment by TornaxO7** [comment]
Alright, thank you!

**Comment by J-Fields** [comment]
@TornaxO7 #5542
