### ISSUE TITLE
Ctrl-A Handled Incorrect

### ISSUE THREAD

**Issue by tiansh** [VSCodeVim/Vim#563]
### What did you do?
With texts:

<kbd>a</kbd> = 1.9

<kbd>a</kbd> means cursor is on letter "a"

Press Ctrl-A

### What did you expect to happen?

Got:

a = <kbd>2</kbd>.9

### What happened instead?

Got:

a = 1.1<kbd>0</kbd>

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.4
* OS: Windows 10.0.10586 (x64)

**Comment by glibsm** [comment]
@sectioneight you might be interested in poking around with this.

**Comment by sectioneight** [comment]
@tiansh can you clarify where your cursor starts? I just double checked and this behaves correctly for me (on OS X) when the cursor is over the `1`, before the decimal.

**Comment by sectioneight** [comment]
Note for others since I won't have time to get to this soon: The bug occurs when you're operating on a decimal with a single-digit prefix, e.g. `1.2` or `9.839` but not `10.2`. It has to do with word matching, where the "iterate words" functionality returns an incorrect range for a single-character "word" (e.g. the `1`) and instead returns `1.` which fails to parse as a number, so we move on to the decimal portion.

**Comment by rebornix** [comment]
This bug is covered by #944 with love from @xconverge .

**Comment by rebornix** [comment]
Fixed in master.
