### ISSUE TITLE
cursor style bug, when I move it to indent position of code line?

### ISSUE THREAD

**Issue by Adolf-L** [VSCodeVim/Vim#5712]
**Describe the bug**

<img width="716" alt="Screen Shot 2020-11-20 at 17 22 22" src="https://user-images.githubusercontent.com/10137107/99783109-f570f500-2b54-11eb-97f3-a658367ad03d.png">

<img width="713" alt="Screen Shot 2020-11-20 at 17 19 28" src="https://user-images.githubusercontent.com/10137107/99782778-8e534080-2b54-11eb-885a-6649181354b4.png">

as you can see.  the block cursor so big, when i move the cursor to Indent position of code line.... Is this a bug? how to fix it?

**Comment by berknam** [comment]
This is normal VSCode behavior. If you disable this extension and set the cursor style to block the same thing will happen. That is happening because the cursor is on top a TAB character `\t` that has size 4, and the cursor always resizes the the character it is on.

You probably have a mix of tabs and spaces in you document. You can fix that by pressing on the bottom bar where it says "Tab Size: 4" and then press "Convert Indentation to Spaces", that turns all tabs in to 4 spaces.

**Comment by J-Fields** [comment]
Yep - this is VSCode behavior, not VSCodeVim behavior and isn't currently changeable, as far as I know.
