### ISSUE TITLE
C-f and C-b keys should page up and down like real Vim

### ISSUE THREAD

**Issue by darrenkenny** [VSCodeVim/Vim#5822]
It would be great if there was an option / preference setting to be able to map C-f and C-b to behave like they do in Vim - for me they are behaving like they do in Emacs, and moving forward and back 1 character.

In Vim, they have always moved forward and back a page, just like page up and down.

This is inconsistent - but looking at other bugs, it looks like people have asked for this behaviour since it's how VSCode works in non-Vim emulation mode.

If you look at:

- ftp://ftp.vim.org/pub/vim/runtime/doc/scroll.txt

you can see how Vim should be working there.

I think a toggle in the options may be the best solution to this - to allow people to choose easily.

Thanks!

**Comment by berknam** [comment]
The keys \<C-f\> and \<C-b\> do behave as PageDown and PageUp. Maybe you have a remap that is changing them or some other extension that is changing their behavior. But by default they move a page down and page up.

**Comment by darrenkenny** [comment]
Hmm not for me...

I tried doing a vim.remap, and got the error that I logged as #5841 - maybe it is related...?

**Comment by darrenkenny** [comment]
These are what I'm seeing when I search for C-f and C-b in the shortcuts - which looks as I think it should be - I don't have that many extensions installed since I only configured this in the last month or 2.

![Screenshot 2020-12-07 at 12 21 37](https://user-images.githubusercontent.com/209306/101350524-00cb5c80-3887-11eb-99ae-97a055c3744e.png)
![Screenshot 2020-12-07 at 12 21 25](https://user-images.githubusercontent.com/209306/101350528-01fc8980-3887-11eb-871b-332f984dc02e.png)

**Comment by berknam** [comment]
Do you have any "Emacs" keymap extension? Because that keybinding of `<C-b>` to `cursorLeft` and `<C-f>` to `cursorRight` that is not native to vscode (AFAIK), that is usually an emacs keybinding. If you have any emacs keybindings then they will collide with Vim keybindings, you can't have both! Those mappings to `cursorLeft` and `cursorRight` are preventing the keys from ever get to Vim extension.

If you don't have installed now but might have installed it before, try checking your extensions folder, in macOS I think it is usually in "~/.vscode/extensions" and see if you have any folder that might be related to an emacs extension.

**Comment by darrenkenny** [comment]
Nope, I don't have any other bindings installed.

BUT, saying that, I just did an upgrade to the latest insiders, which also updated to the latest Vim extension released today 1.18.4, and hey-presto, it is working as I expected.

Not sure which one fixed it, but the entries in the shortcuts are still the same.

Thanks for you help, I guess this can be closed now.
