### ISSUE TITLE
Cannot read property 'after' of undefined

### ISSUE THREAD

**Issue by darrenkenny** [VSCodeVim/Vim#5841]
**To Reproduce**

I'm running VSCode Insiders on Mac:

```
Version: 1.52.0-insider
Commit: 532ba43c78c82b24bdf94f9edde30cdf9b9bfa12
Date: 2020-12-05T01:08:42.214Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

1.  Run the action "Vim: Remap key combination  that VS Code supports as Vim ..." (vim.remap)
  - I did this because of my request for the feature for #5822 where it was said that C-f and C-b should be working as page up/down - but I'm not seeing that. I then tried to do this remap, and saw the error - I'm wondering if that is related then.
2.  See error

**VSCodeVim version**: 1.18.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'after' of undefined
    at Object.promise (/Users/darrenk/.vscode-insiders/extensions/vscodevim.vim-1.18.0/out/extension.js:9:229185)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (/Users/darrenk/.vscode-insiders/extensions/vscodevim.vim-1.18.0/out/extension.js:11:285853)
```

</details>

**Comment by berknam** [comment]
@J-Fields This might be the cause of all this "Cannot read property 'after' of undefined". The reason is that the users are trying to call the "Vim: Remap..." command from command palette. But this command is not supposed to be called directly. It is supposed to be used from keybindings in 'keybindings.json'. We can simply remove it from the 'package.json' file here:
```json
  "contributes": {
    "commands": [
      {
        "command": "vim.remap",
        "title": "Vim: Remap any key combination that VS Code supports to Vim motions/operators/ExCommands/macro."
      },
```

This way we can still use it from keybindings but not directly from the command palette.
