### ISSUE TITLE
Default useCtrlKeys to true on OSX

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#595]

**Comment by sectioneight** [comment]
So I started looking into this, but even without anything in `settings.json`, `vscode.workspace.getConfiguration("vim")` returns a hash with `useCtrlKeys`: `false`. I'm guessing that's because it's defined as a boolean. Is this a limitation in the VSCode API? Is there any way to check whether a key was provided? Something like a nullable boolean cc @rebornix

**Comment by rebornix** [comment]
@sectioneight Code will set a default value for configurations if Extension put it in the contribution list. And you have a correct feeling about this, currently we are lack of enough info about whether a config is set by User or Workspace or it's just default. This feature request is tracked by https://github.com/Microsoft/vscode/issues/10583 .

**Comment by sectioneight** [comment]
Cool, I'll subscribe to that issue and once resolved pick this one back up.

**Comment by rebornix** [comment]
@sectioneight oh cool, I'll make sure I don't steal it from you :)

**Comment by rebornix** [comment]
Just played with latest release, and I can use ctrl keys directly without any config on Mac.

**Comment by xconverge** [comment]
@johnfn we can close this is we set it to true for everyone ;)
