### ISSUE TITLE
In Visual Mode, Ctrl+v paste, like VsVim

### ISSUE THREAD

**Issue by Yusheng9966** [VSCodeVim/Vim#598]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?
i selected som text and type Ctrl + C, copy the text to the clipboard, then 
i selected some other text by mousing, and type Ctrl+v, 

### What did you expect to happen?
i excpect this is a paste operation.
### What happened instead?
nothing happend now

### Technical details:

* VSCode Version: 0.1.6
* VsCodeVim Version: *[please ensure you are on the latest]*
* OS: Windows 7

**Comment by MaxTan** [comment]
How to disable "--VISUAL BLOCK MODE--" ?

**Comment by johnfn** [comment]
Ahh - for a while there, I believed that this was a different bug, but now I see that the bug is that we are triggering visual block mode when you use ctrl-v and haven't enabled useCtrlKeys. That is actually pretty bad. 

I've fixed that and will be releasing a new version soon. Thanks for the report. :)
