### ISSUE TITLE
'u' and 'ctrl-z'

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#600]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

Maybe same root cause as [#565](https://github.com/VSCodeVim/Vim/issues/565), but just report it first.

### What did you do?

`i` to insert some text
`u` to undo
`ctrl-z` to undo

### What did you expect to happen?

nothing, no change to the text

### What happened instead?

`ctrl-z` redos `i`

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.6
* OS: Windows 10 professional

**Comment by johnfn** [comment]
The reason this happens is because we keep history separate from VSCode.

I don't want to fix it because in the rare case where we mess up history, you can always retrieve it by using VSCode's ctrl-z - it's more of a feature than a bug.

When VSCode releases history tracking, this will cease to be a problem. :)

**Comment by offero** [comment]
I'm having this problem too. I never know whether to use u or ctrl-z. Sometimes u just doesn't work for me and I have to ctrl-z all the way back.

So it's difficult for you to make u do what ctrl-z does at the moment?

**Comment by johnfn** [comment]
@offero If u does something different than ctrl-z, that's a bug. Please report it!! :)
