### ISSUE TITLE
The message on the status bar about how many to look for conflicts with "Normal"

### ISSUE THREAD

**Issue by ElevenIjusee** [VSCodeVim/Vim#6039]
when i use "/","#""*" to search, The message on the status bar about how many to look for conflicts with "Normal" and flashes back and forth

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.50.1
- OS: win 10

**Comment by sethmnielsen** [comment]
I also have this issue. VSCodeVim 1.19.3, VSCode 1.54.3, OS: Arch Linux.

I noticed that it occurs only when the next match is off the page, i.e. requires the editor to scroll in order to show it. It usually will try to display the number of matches, but the "-- NORMAL --" very quickly replaces it. If the next match is within the currently visible code, then it will show "match __ of __" as expected. It happens for me in both normal and visual modes.
