### ISSUE TITLE
L (in normal mode) move cursor to bottom-line + 1

### ISSUE THREAD

**Issue by Bingularity** [VSCodeVim/Vim#606]
### What did you do?
L (in normal mode)

### What did you expect to happen?
Cursor moved to the last visible line

### What happened instead?
Cursor moved to the line below the last visible one and that line is pulled-up (screen scrolled-up). (Happened in Window mode as well as Full Screen mode)

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.6
* OS: Mac OS X 10.11.6 (El Capitan)

**Comment by johnfn** [comment]
That's weird. We just use builtin VSCode methods for this one, so it's almost certainly a VSCode bug.

@rebornix how do you feel about reporting this as a vscode bug vs mitigating it ourselves?

**Comment by rebornix** [comment]
@johnfn @Bingularity I noticed this issue when I implemented these screen lines related commands. Firstly it has nothing to with our code as we are leveraging Code's API. But to VS Code, it is likely a `by-design`. The root cause is Code allows part of the screen line to be hidden like below:

![image](https://cloud.githubusercontent.com/assets/876920/17654365/f3041ad8-62d4-11e6-969e-e016a80c2fe9.png)

Part of Line 31 is hidden due to the actual height of my Code's window. This is impossible in Vim as each line in the viewport should be shown fully or just totally hidden. Code and Vim are just doing differently when drawing lines inside a viewport.

This is when Code behaves differently with Vim. Personally I'm Okay with Code's way and I'd like to mark it as `low-priority` but let me know what's your opinions on this.

**Comment by Bingularity** [comment]
I've tried it with status-bar off and got the same result. It looks like Code just doesn't let us place the cursor on the last visible line and keeps scrolling the last line up for us. And it's the scrolling that is not logical to me because H/M/L are for cursor placement.

I tried PgDn and Code placed the cursor on the second last line. Can we do the same? Use that same line as the reference point (e.g. 2L will place the cursor two lines above that.) That way, we can keep the page from scrolling.

By the way, I'm okay with 'low-priority' because this is not a big issue. I just don't want to lose the top whenever I go bottom :)

**Comment by johnfn** [comment]
@rebornix Like @Bingularity was saying... it seem to consistently be 2 lines lower than it should - could we just run L, then move it up two lines?

**Comment by Bingularity** [comment]
@rebornix I'm not sure if this will help or not.

From studying class **MoveToLineFromViewPortBottom** and **MoveByScreenLine**, I believe that the final work is done in VSCode in method **OneCursorOp**.[move()](https://github.com/Microsoft/vscode/blob/1.4.0/src/vs/editor/common/controller/oneCursor.ts#L720) where the target line number is obtained from calling _cursor.getLineFromViewPortBottom(moveParams.value)_.

If that is the case, can we pass the offset (i.e. 1 or 2) in? If we pass _this.noOfLines_ to **value** instead of **noOfLines** in _actions/actions.ts_ [line 2037](https://github.com/VSCodeVim/Vim/blob/v0.1.6/src/actions/actions.ts#L2037), will it be available to VSCode above?

**Comment by rebornix** [comment]
Per current behavior, this issue was gone.

**Comment by ganesh-reddy-b** [comment]
This issue stills persists. could you please once check.

**Comment by jspeaks** [comment]
Still seeing this issue today, 9.28.2023. L shifts the observable lines down one line on each press.
