### ISSUE TITLE
`<` followed by `<CR>` in remap parsed incorrectly

### ISSUE THREAD

**Issue by Dylan-Kerler** [VSCodeVim/Vim#6153]
**Describe the bug**
Tried to do a remapping in vimrc: `nnoremap [ /< <Cr>`.
Expected it to search for "<" when pressing "[" but instead it searches for "< ^M". 
It looks like "\<Cr>" is being turned into "^M".

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS: Ubuntu

**Comment by sql-koala** [comment]
Hi,
the title is a bit misleading, but i can repro the issue. The problem seems to be, to have
- a mapping in vimrc
- which enters commandline/search
- and ends with cr to confirm

A workaround is possible:
```
        {
            "before": [")"], "after": ["/", "<", "<cr>"]
        },
```
This helped me solve a similar issue i had, where i want a mapping to call bang :! and run it with cr.
