### ISSUE TITLE
Ctrl-A/X not working correctly if the numbers aren't surrounded by separators

### ISSUE THREAD

**Issue by stefanoio** [VSCodeVim/Vim#638]
### What did you do?
I used Ctrl-A on something like `width: 2em;` or `abc1`.

### What did you expect to happen?
They should have changed to `width: 3em;` and `abc2`.

### What happened instead?
Nothing

### Technical details:
none

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Mac OSX 10.11.6 (15G31)

**Comment by xconverge** [comment]
Yep I reproduced this easily if the number is not separated by some character like a space or colon.

Good find

**Comment by stefanoio** [comment]
I use it a lot (mainly in css) so I noticed it immediately. I think it relates to #563. BTW, thank you for the work you are putting in this project!

**Comment by sectioneight** [comment]
It's semi-related to #563 (although that's mostly just a bug in handling single-character ranges). I totally forgot about this use case when implementing. We're probably going to have to change the search mode for numerals from "word boundaries" to "anything that's not a number", since hitting `ctrl-a` on `123foo` should work.
