### ISSUE TITLE
Failed to handle key `<C-o>`. Could NOT open editor for...

### ISSUE THREAD

**Issue by yueyingjuesha** [VSCodeVim/Vim#6445]
When use search editor and jump to a specific file, when jumping back using <C-o>, this error is poping up

**Comment by begin29** [comment]
@J-Fields you have closed my issue request as a duplicate of that issue. 
And also closed that issue with fix from November with that code https://github.com/VSCodeVim/Vim/commit/35faa9209b3d9dbd21b315db00f798e903073e41

But the issue is still reproducable. I have used a fresh version of the extension. v1.21.10

**Comment by J-Fields** [comment]
Indeed, the last release was in October. Unfortunately I've been concentrated on other things for the past few months so haven't managed a release, but plan on fixing that soon.
