### ISSUE TITLE
gq overrides all spaces according to joinspaces, not just at line boundaries

### ISSUE THREAD

**Issue by kainino0x** [VSCodeVim/Vim#6569]
**Describe the bug**

> I don't know if it was due to this patch #5895 or a later one, but I recently found that e.g. `gqq` replaces all whitespace after a `.` with an exact number of spaces (1 or 2), throughout the paragraph. This differs from Vim, which appears to preserve all internal spaces (unless they get turned into a line break), using `joinspaces` only to determine whether a `\n` should be replaced with one space or two spaces.

_Originally posted by @kainino0x in https://github.com/VSCodeVim/Vim/issues/5895#issuecomment-828695384_

**To Reproduce**

1.  Check joinspaces value (doesn't matter which)
2.  Open a buffer, insert
```
Good morning, how are you?  I'm Dr. Worm.
I'm interested
in      things.
```
3.  press `gqip`
4.  Observe either of the following depending on joinspaces value:
```
Good morning, how are you? I'm Dr. Worm. I'm interested in things.
```
```
Good morning, how are you?  I'm Dr.  Worm.  I'm interested in things.
```
Note that the spaces within the lines have all been reset (incorrectly, in the case of `Dr.`).

**Expected behavior**
Vim produces the following results:
```
Good morning, how are you?  I'm Dr. Worm. I'm interested in      things.
```
```
Good morning, how are you?  I'm Dr. Worm.  I'm interested in      things.
```

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.20.1`
- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.55.2`

<details><summary>json</summary>

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 75,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscodevim.vim",
				"_lower": "vscodevim.vim"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

</details>

**Additional context**
I think this started happening in the last week or so.

**Comment by nomad-software** [comment]
This is definitely a recent change. I've noticed that when performing `gq` on a selected line in a markdown document it inserts a double space after every full stop (period).

I've just tested it with python code and it also inserts double spaces in comments too.

If this is an intentional change can we please revert this behaviour?

**Comment by nomad-software** [comment]
Can this be defaulted to `false` please? This is breaking behaviour for all users. Now everyone will have to add a config option to revert back.

**Comment by edemaine** [comment]
For what it's worth, I think #5895 was responsible only for the double spacing after the periods.  I just tested rewinding to a version from December 6 and it has the same behavior of compressing all the spaces between `in` and `things`.  That code seems to go back to 2017.

I imagine you're just noticing the normalization of interword spacing more often because of the new `joinspaces` option (and that's understandable).

Given that I'm familiar with the code, I'm hoping I can fix it.

**Comment by nomad-software** [comment]
> You can turn off this functionality via :set nojoinspaces.

Yeah that's correct and I have done. Thankfully this is an option. But... this is a breaking change for everyone who uses this extension. Everyone is now required to do this. Surely it would have been better to be opt-in and change the default to false.

**Comment by kainino0x** [comment]
FYI the vast majority of people in the US don't use double space anymore either. It was more common when Vim's defaults were originally set :)
