### ISSUE TITLE
Support `<C-g>u` in Insert mode

### ISSUE THREAD

**Issue by searleser97** [VSCodeVim/Vim#6612]
**Describe the bug**
the following mapping adds the ability to undo word by word
`inoremap <Space> <Space><C-g>u`

when I use it with this extension it inserts the letter "u" which is not expected.

**To Reproduce**

1.  Add the specified mapping
2. start writing a word and press <space> key

**Expected behavior**

should not insert the letter "u" and be able to undo word by word.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: Latest
- VSCode version: Latest
- OS: MacOS, Linux and Windows

**Additional context**

**Comment by carwyn** [comment]
Worth tagging this with the label "area/undo"

**Comment by J-Fields** [comment]
Documentation: https://vimhelp.org/insert.txt.html#i_CTRL-G_u

**Comment by searleser97** [comment]
Any updates on this ?

If not, could someone give any start point to see if I can contribute with this ?

**Comment by J-Fields** [comment]
@searleser97 I'll get around to it eventually if nobody else does, but not WIP at the moment.

`HistoryTracker.finishCurrentStep` marks an undo step, so `<C-g>u` should cause it to be called immediately (rather than when we exit insert mode). Unfortunately the code surrounding this is a bit of an opaque mess (even after recent refactors), so for one reason or another just calling it directly may fail miserably. Feel free to dig in and let me know if you get stuck!

**Comment by searleser97** [comment]
I discovered a workaround for this, adding the following key bindings do the job.

```json
"vim.normalModeKeyBindings": [
        {
            "before": ["u"],
            "commands": [
                "undo"
            ]
        },
        {
            "before": ["<C-r>"],
            "commands": [
                "redo"
            ]
        }
]
```
