### ISSUE TITLE
Can't use my .vimrc mappings and configuration on windows

### ISSUE THREAD

**Issue by pserey** [VSCodeVim/Vim#6771]
I've set my `.vimrc` in my windows `$HOME` directory (`C:/Users/myuser`) and the extension recognizes it but always gives me a error message saying:
```
vimrc file "C:\Users\serey" is broken, err=Error: EISDIR: illegal operation on a directory, read

Source: Vim (Extension)
```
![image](https://user-images.githubusercontent.com/65696885/122682081-d3fce800-d1cd-11eb-8905-dbc9711b79f0.png)

The same .vimrc worked perfectly in my ubuntu machine without the error message, do you have any idea of what would be this error? I've already tried renaming it with and without the . in front and nothing :/

**Comment by northernocean** [comment]
how exactly did you set your .vimrc in your $HOME directory. In principle, you shouldn't need to do that at all since it will look there by default. Did you put a vimrc filepath in your settings? If so, what did you put there? I found it best to either not specify a file path or to use a unix-style path: /Users/MyName/.vimrc

You may also have to check the setting to use vimrc. See:
https://stackoverflow.com/questions/63017771/how-to-modify-change-the-vimrc-file-in-vscode

**Comment by pserey** [comment]
Hello! I've tried that too and it didn't recognize my `.vimrc` file. But I did got to configure the extension in VScode's `settings.json` and it's working well haha. Thank you very much!
