### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#700]
**Tests are too slow:**
- [ ] Don't create a new file every time, 
- [ ] Don't insert all the text character by character and don't then manually keystroke to the right position - insert it all immediately and then set the position to the right location.

**Tests are not comprehensive enough**
- [ ] Test for command remapping
- [ ] Test for visual block mode
- [ ] Test for undo, especially all the wonky undo behavior we added recently.
- [ ] Test for .vimrc settings

**Tests have weird behavior**
- [ ]  Handle all the what in god's name errors being thrown by the tests. They don't affect the test's results, but they are annoying

**Comment by infogulch** [comment]
Sure! Sorry for vanishing, life got the better of me. :)

All of the work I was doing on this is on the [test-cleanup](https://github.com/infogulch/Vim/tree/test-cleanup) branch of my fork, in the [latest commit](https://github.com/infogulch/Vim/commit/bb2929435586a70ba51ae463120c2e426c14f0d0).

But I was never able to get it working 100% (a couple of tests failed). And I'll be honest, I'm not very sure where the "correct" place would be to hook in to set the text and cursor state and make sure everything is synced up, I basically just hacked it until it appeared to work. :)

However, ignoring the couple of failing tests (because pssh who cares about those, right?) this does speed up the test suite by about 3x.

**Comment by jpoon** [comment]
A couple of other things we could do:

[] Handle all the `what in god's name` errors being thrown by the tests. They don't affect the test's results, but they are annoying

**Comment by johnfn** [comment]
No worries, @infogulch! Super appreciative of all the work that you did manage to do. :)

**Comment by johnfn** [comment]
Actually @jpoon could you open up a separate issue for that one?

**Comment by rebornix** [comment]
I'll suggest have a test project and putting pre-inserted text into files then open those files to run motions directly, which can definitely reduce the time of text inserting.

**Comment by infogulch** [comment]
@rebornix That would definitely be better than the current situation, but the method in my branch sets the text buffer directly, I doubt it could get much faster than that.
