### ISSUE TITLE
Can't install in Azure Data Studio from VSIX package

### ISSUE THREAD

**Issue by msturkorean** [VSCodeVim/Vim#7079]
**Describe the bug**
Azure Data Studio won't install version 1.21.7 

**To Reproduce**
Azure Data Studio allows VS Code extensions to be installed by downloading the VSIX package from the marketplace and then installing it by going to File>Install Extension from VSIX package.

1.  Go to the VS Code Marketplace page 
2.  Click on "Download Extension" on the right sidebar under Resources to download VSIX pkg
3.  In Azure Data Studio, go to File > Install Extension from VSIX package
4.  See error: "Unable to install extension 'vscodevim.vim' as it is not compatible with the current VS Code engine version '1.56.0'." 

**Expected behavior**
Should install and prompt to reload

**Screenshots**
None

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.7
- ADS Version: 1.32.0
- OS: Mac OS Big Sur

**Additional context**

**Comment by elazarcoh** [comment]
If I understand correctly, you're seeing this because vscodevim is targeted for a higher version of vscode (currently to 1.57), while datastudio is using lower version of the engine (couldn't find the exact one in the code, but from the error it probably is 1.56).

You can always download a previous version of vscodevim (you can look in the package.json for the engine version), while waiting for datastudio to catch up with vscode.
You might even be able to build from vscodevim from source, while targeting for 1.56 instead, but no promises (e.g. if the API has changed or something)

**Comment by msturkorean** [comment]
Oh DUH!! Because of the wording of the error, I thought it was saying 1.56 was current. Thanks!
