### ISSUE TITLE
`<C-Up>` and `<C-Down>` cause editor to enter Visual mode 

### ISSUE THREAD

**Issue by I-3B** [VSCodeVim/Vim#7254]
**Describe the bug**
I use [Incrementor](https://marketplace.visualstudio.com/items?itemName=nmsmith89.incrementor) and this extension makes use of Ctrl + up and Ctrl + down for incrementing and decrementing numbers, when I try using it vim enter visual mode.

**To Reproduce**

1.  install  [Incrementor](https://marketplace.visualstudio.com/items?itemName=nmsmith89.incrementor)
2.  open for example a JSON file and try to increment or decrement a number value using <C-Up> or <C-Down>
3.  it should now enter visual mode

**Expected behavior**
vim should not enter Visual mode when pressing <C-Up> or <C-Down>

**Environment:**

- Extension (VsCodeVim) version: 1.21.10
- VSCode version: 1.62.2
- OS: Windows 10 Build 19043

**Additional context**
of course, when I disable this extension this don't happen.
Thanks in advance!!

**Comment by J-Fields** [comment]
My guess is that Incrementor [changes the editor selection](https://github.com/nmsmith22389/vscode-incrementor/blob/master/src/Adjustment.ts#L163). We don't have much context as to what actually happened on our side, and because Select mode isn't currently implemented, we don't have much choice but to go into Visual mode. There are lots of existing issues with the same underlying cause (#6619, for instance), so I'm closing this as a duplicate.
