### ISSUE TITLE
Mapping <C-k> but " Ctrl+k was pressed. Waiting for second key of chord " happens.

### ISSUE THREAD

**Issue by AlexString** [VSCodeVim/Vim#7350]
**Describe the bug**
I would like to map `<C-k>` but I get this message that says it's waiting for a second chord.

**To Reproduce**
```json
// In settings.json

{ // This works
  // Move down faster
  "before": ["<C-j>"],
  "after": ["8","j"]
},

{ // Move up faster
  "before": ["<C-k>"],
  "after": ["8","k"]
}
```

**Expected behavior**
Move 8 lines up using `<C-k>`. Already tried excluding the keybinding in `vim.handlekeys`

```json
"vim.handleKeys": {
 "<C-k>": false,
}
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.10
- VSCode version: 1.63.0
- OS: Linux

**Comment by w-cantin** [comment]
Hello, make sure to put vim.handlekeys to true and not false. Like this:

```json
"vim.handleKeys": {
 "<C-k>": false,
}
```

**Comment by northernocean** [comment]
These key bindings work for me.

My setup (on linux) is that I made no special setting for vim.HandleKeys (so I guess I have the default, whatever that is).
I also have the setting for Use Ctrl Keys set to true (I think this is also the default). I just check this on or off in the GUI settings, and I think on is the default because there is also nothing explicit in settings.json.

Note that if I uncheck Use Ctrl Keys then I do get the behavior you describe ("waiting for second key of chord") - although with both mappings, Ctrl-J and Ctrl-K.

**Comment by AlexString** [comment]
@northernocean 
> Note that if I uncheck Use Ctrl Keys then I do get the behavior you describe ("waiting for second key of chord") - although with both mappings, Ctrl-J and Ctrl-K.

The thing is I got 'Use Ctrl Keys' checked, tried unchecking like you said and get the same behavior, only this time `<C-j>` does not go 8 lines down.
In other words, even with 'Use Ctrl Keys' checked says "waiting for second key of chord"

@w-cantin 
> make sure to put vim.handlekeys to true and not false.

Hello, I tried with `true` before, so I thought `false` would do something.
I am still getting that "waiting for second key of chord" message, is there any way to disable it?

I'm letting here my config file If you want to take a look:

https://gitlab.com/AlexString/vscode-keybindings/-/blob/master/settings.json

(Sorry if it sees some weird indentations, I don't know why GitLab does this)

**Comment by northernocean** [comment]
I copied your settings.json verbatim as my vscode settings and the only thing I can say is that I didn't encounter any issues - Ctrl-k and Ctrl-k both jump 8 lines up or down.

**Comment by w-cantin** [comment]
I can't reproduce the issue either. It might be a linux issue (I am using Windows) or it might be because the keybinding was overwrited somewhere else. When you open [VSCode's keyboard shortcuts](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor) and search specifically for the command:
`extension.vim_ctrl+k` is it bound to `Ctrl+K`?

**Comment by AlexString** [comment]
**[Solved the problem]** I need to apologize for making you guys spend time trying to help me, I thank you so for being supportive and giving me some hints that helped me.

### The issue:

The issue was that I had a certain keybinding on `keybindings.json` that involves `Ctrl + k` + other keybinding:

```json
// - Fold all: block comments
{ "key": "ctrl+k ctrl+shift+7",   "command": "editor.foldAllBlockComments",
                                 "when": "editorTextFocus && foldingEnabled" },
```

> Ctrl+k was pressed. Waiting for second key of chord

This was the thing that makes the message appear.

With deleting that keybinding I got the expected behavior.
