### ISSUE TITLE
Type lower case "j" in insert mode has strange cursor behavior.

### ISSUE THREAD

**Issue by yorkz1994** [VSCodeVim/Vim#7351]
**Describe the bug**

When in insert mode, type lowercase letter "j" , you can see the letter appears first, but the cursor is still at the left side of the letter typed and after a while, the cursor will move to the right side of the letter. Seems only letter "j" has this strange problem.

**To Reproduce**

1.  Go to insert mode, e.g. type "i" in normal mode.
2.  Type lower case letter "j"
3.  See error

**Expected behavior**
After typed the letter, the cursor should move to right side of the letter at once, not after a while.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.10
- VSCode version: 1.63.2
- OS: Win10

**Additional context**

**Comment by jurgen-kluft** [comment]
Take a look in your settings.json, the following:
  "vim.insertModeKeyBindings": [
    {
      "before": ["j", "j"],
      "after": ["<Esc>"]
    }
  ],

This means that the 'j' key is treated in a special (time) manner in that it will take a certain delay for the cursor to move on. If in the time window you press j again the ESC key is actually activated.

**Comment by northernocean** [comment]
I can confirm this matches the behavior as in vanilla vim.

I've had _aa_ mapped to ESC for years and the behavior is the same. It's generally not a problem for me unless I actually intend to type the letters _aa_ - something rather rare. I suppose _jj_ is similarly unusual (I have known a few programmers who like to pair _i_ with _ii_ and _j_ with _jj_ in nested loops so that could be a reason not to go for this particular keybinding)
