### ISSUE TITLE
Plugin doesn't work with VSCode version: 1.63.2

### ISSUE THREAD

**Issue by vcarnogu** [VSCodeVim/Vim#7430]
**Describe the bug**
Plugin not working with VSCode version: 1.63.2

**To Reproduce**

1.  Start VS Code with a file `code dummy.txt`
2.  Press `Esc` key to enter vim Normal mode
3.  Press `/` to start searching
4.  Character `/` is printed in opened file in instead of Normal mode command line.

**Expected behavior**
Vim Normal mode should be entered on `Esc`.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.10
- VSCode version: 1.63.2
- OS: MacOS BigSur 11.6

**Additional context**
Removed all plugins from VSCode didn't help. 
Re-installing plugin didn't help.
Changing mapping from `Esc` to another key didn't help.

Downgrade to an older version of VSCode helped (v1.61.2).

**Comment by alexkubica** [comment]
Can confirm on  1.64.0 too

**Comment by bhavitsharma** [comment]
I downgraded the extension to 1.21.10 and it works!

**Comment by byongwu** [comment]
I just checked VSCode v1.64.1 (latest) and VSCodeVim v1.22.1 (latest) works. Thank you!

**Comment by tyleryoungblood** [comment]
I'm still having the same issue. 
I've tried deleting my ~/.vscode/extensions folder, didn't help. 
I've tried downgrading VSCodeVim to 1.21.10 (and other older versions, didn't help. 
I've downgraded VSCode to 1.61.2, didn't help.
I've tried remapping my insert key via Keyboard Shortcuts, as well as by editing Code/User/settings.json - didn't help. 

I'm really bummed because I have a very repetitive file edit to do that will just be miserable if I'm forced to use the mouse. Lol.

**Comment by tyleryoungblood** [comment]
Ok, I was getting a "No .vimrc found. Please set `vim.vimrc.path.`" alert message in the lower right corner of VSCode. Once I noticed that I was able to disable (uncheck) "Use key mappings from a .vimrc file." and that seems to have fixed the issue. I don't remember ever checking/enabling that. So that surprised me. Should I care about a .vimrc file if I want to use vanilla Vim commands? That's only for custom configuration, right?

**Comment by vcarnogu** [comment]
I just checked VSCode v1.64.1 (latest) and VSCodeVim v1.22.2 (latest) works again.
