### ISSUE TITLE
s/a/b/g does not work over multiple lines

### ISSUE THREAD

**Issue by uitgewis** [VSCodeVim/Vim#761]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Select multiple lines: `V2j`
2. Replace a term globally for selection: `:s/a/b/g`

### What did you expect to happen?
Replaces all occurrences of `a` with `b` for the selection.

### What happened instead?
Only replaces occurrences on the first line selected.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: macOS 10.11.6

**Comment by rebornix** [comment]
When you select lines by `V2j` and run `:`, we put a placeholder `'<,'>` there for your selection, which is the same behavior in Vim. But for now the placeholder in the popup window is selected, so you might happen to replace them with `s/a/b/g` directly instead of keeping them as a prefix. `:s/a/b/g` will only take effect on the first line, which is the same as Vim and `'<,'>s/a/b/g` will take effect on all lines.

This problem was initially raised in https://github.com/VSCodeVim/Vim/issues/512#issuecomment-238644421 and we have filed feature request for Code https://github.com/Microsoft/vscode/issues/10582 .
