### ISSUE TITLE
Replace mode can't replace character with 'j' or 'k'

### ISSUE THREAD

**Issue by happyTonakai** [VSCodeVim/Vim#7833]
**Describe the bug**
Cannot replace character with 'j' or 'k' in replace mode.

**To Reproduce**

1.  Press `esc` to enter normal mode
2.  Press `r` to enter replace mode
3.  Hit `k` or `j`
4.  The cursor jumps up or down

**Expected behavior**
The current character is replaced with k or j

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.23.1
- VSCode version: 1.69.1
- OS: Win10 21H1 19043.1826

**Comment by nickgerlock** [comment]
Hi, I'm experiencing this same issue, and I think I know the cause in my case (though I'm unsure of how to solve it). In my case, it is caused by having added these commands to `keybindings.json` in order scroll through lines visually when single lines are split via word wrapping.
```
  {
    "key": "up",
    "command": "cursorUp",
    "when": "editorTextFocus && vim.active && !inDebugRepl && !suggestWidgetMultipleSuggistions && !suggestWidgetVisible"
  },
  {
    "key": "down",
    "command": "cursorDown",
    "when": "editorTextFocus && vim.active && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "k",
    "command": "cursorUp",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Normal' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "j",
    "command": "cursorDown",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Normal' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
```

It's strange. This issue happens because when doing a one-character replace with `r`, VS Code/Vim is still in `NORMAL` mode. If there is any way to detect whether it is currently in "one-character replace" mode, then this could easily be fixed.

**Comment by MarcoIeni** [comment]
> This issue happens because when doing a one-character replace with r, VS Code/Vim is still in NORMAL mode.

I had the same problem. I looked at the code base a bit. The issue is that when we press `r` [here](https://github.com/VSCodeVim/Vim/blob/15dbe0b415f269a5be14dc74651a69b9334fba14/src/actions/commands/actions.ts#L1657) we don't edit the state, while for example when we press `R` we do (see [here](https://github.com/VSCodeVim/Vim/blob/15dbe0b415f269a5be14dc74651a69b9334fba14/src/actions/commands/actions.ts#L503)).

> If there is any way to detect whether it is currently in "one-character replace" mode, then this could easily be fixed.

Exactly, ideally after we press the first `r` we should edit the state. E.g. `vim.singleReplace == true`.
