### ISSUE TITLE
[BUG/Question] Custom keybindings overwriting vim motion

### ISSUE THREAD

**Issue by FrancescoLuzzi** [VSCodeVim/Vim#8476]
**Describe the bug**

Added theese keybindings in `keybindings.json`
```json
{
  "key": "shift+L",
  "command": "workbench.action.nextEditorInGroup",
  "when": "editorTextFocus && inputFocus && vim.mode == 'Normal'"
},
{
  "key": "shift+H",
  "command": "workbench.action.previousEditorInGroup",
  "when": "editorTextFocus && inputFocus && vim.mode == 'Normal'"
},
```
This works fine until you have to perform a `f/t/F/T` motion, the motion is ignored and the keybinding is executed.
Adding `vim.mode != 'OperatorPendingMode'` doesn't resolve the problem.

**To Reproduce**

1.  apply my custom keybindings
2.  press `fL` to search for the next `L`
3.  editor will switch instead

**Expected behavior**
Editor should not switch and cursor is now on `L`

> If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

I followed the intructions but i wasn't able to enable debug logging, sorry 🙃 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.25.2
- VSCode version: 1.79.2
- OS: windows 10

Have a good one 😄

**Comment by MasterTemple** [comment]
I ran into a similar issue. Here is a workaround:

Place the following in your `settings.json`:

```json
{
  "vim.normalModeKeyBindings": [
    {
      "before": ["shift+l"],
      "commands": ["workbench.action.nextEditorInGroup"],
    },
    {
      "before": ["shift+h"],
      "commands": ["workbench.action.previousEditorInGroup"],
    },
  ],
}
```

This way `shift`+`l`/`h` will only be considered when not in the middle of a motion, such as `fL`.

If you want a command that will also work outside of being in an editor window, you will have to register 2 commands.

Example:

I wanted to use `space f f` (` ff`) to find files.

So I had to put this in `settings.json` (so that I could still do the vim motion `f ` without ` ff` messing it up)

```json
{
  "vim.normalModeKeyBindings": [
    {
      "before": ["space", "f", "f"],
      "commands": ["workbench.action.quickOpen"],
    },
  ],
}
```

and this in `keybindings.json` (so that I could use ` ff` when I have no text editors open)

```json
{
  {
    "key": "space f f",
    "command": "workbench.action.quickOpen",
    "when": "!editorTextFocus"
  },
}
```

**Comment by FrancescoLuzzi** [comment]
Thanks, that makes sense...
I'm just being a silly annoying user 😄 

![image](https://github.com/user-attachments/assets/a4e5f672-8864-4e6b-a521-363f15f16c64)
