### ISSUE TITLE
korean typing error

### ISSUE THREAD

**Issue by astrataraxia** [VSCodeVim/Vim#8577]
**Describe the bug**

**There is a typing error in Korean.** It keeps breaking weirdly when I type in Korean. This error occurred after the vscode update, so I thought it was a vscode problem, but when I deleted the vim and used it, it worked fine. So I don't know exactly which error it is, but I think I need an update from vim.

**To Reproduce**

Just typing Korean
 -> typing : 안녕하세요 
 -> But typing : ㄴ안ㄴ세하세요 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version: 1,82.0
- OS: window 11

**Comment by cake-monotone** [comment]
I'm experiencing the same issue on a Mac. Korean characters are being decomposed or not inputted correctly.

I think this is a bug related to the vim-extension version 1.26.0, and not with VSCode itself.

I installed version 1.25.2 and confirmed that the issue doesn't exist there.

**Comment by SE-June** [comment]
I have the same issue on typing in Korean

**Comment by eduardosilva** [comment]
I think this is not a specific error when typing in Koren because I have the same issue typing in English or Portuguese (pt-br)

**Comment by okamototomoyuki** [comment]
Japanese input also frequently becomes incorrect.
Although the Japanese input system involves entering alphabets and converting them to Japanese words with the same pronunciation,
the position of the character replacement often becomes incorrect.

**Comment by shinypond** [comment]
I have the same issue when typing in Korean.

**Comment by Kimnabin** [comment]
Since it may take some time to be fixed, here's a small workaround: use previous version
I deleted the vim extension from VSCode and ran this command in the terminal.

code --install-extension vscodevim.vim@1.25.2

This should do until the issue is resolved.
Happe Coding.

for Mac users

to enable the code command in the terminal, you need to cmd + shift + p and choose Shell Command: Install 'code' command in PATH
also cmd + shift + p and select Extensions: Disable Auto Update for All Extensions to prevent auto update

Or add Vim Extensions ver 1.25.2

![Screenshot 2023-09-16 012845](https://github.com/VSCodeVim/Vim/assets/96113006/c01bfaf3-fa02-4d70-a352-a3c443b2ac06)

**Comment by ianhenrygim** [comment]
@Kimnabin The solution you gave works. Thanks.

**Comment by NeuroWhAI** [comment]
Same here.

**Comment by thisnome94** [comment]
@Kimnabin 감사합니다.

**Comment by KIM-HYUN-H0** [comment]
@Kimnabin Good Solution !

**Comment by minwoogramer** [comment]
> @Kimnabin The solution you gave works. Thanks. 

Hi Henry! Can I contact you?

**Comment by sooohka** [comment]
Hi, i'm experencing same issue on v1.27.2, any changes?
