### ISSUE TITLE
Insert mode keystrokes are sometimes dropped since 1.26.0

### ISSUE THREAD

**Issue by TommyX12** [VSCodeVim/Vim#8603]
**Describe the bug**
In the latest release version of vscode vim, when I type in insert mode, about 50% of the time one or more of the characters I input will be missing. The problem is worse when there are heavy auto-complete or github copilot completions. Reverting to 1.25.2 solves this issue.

**To Reproduce**
1. Open a file (preferably within an existing project).
2. Go to insert mode, very quickly type "asdfghjk".
3. Notice that some of the characters are missing.

**Expected behavior**
The typed string should always be "asdfghjk".

**Environment:**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version: 1.82.2
- OS: Windows 10

**Comment by nikitavoloboev** [comment]
This is incredibly frustrating. Please fix this.

https://github.com/pqrs-org/Karabiner-Elements/issues/3595

Hitting the issue above, I can't automate keypresses with this extension on.

Is it possible to downgrade to earlier versions?

**Comment by nikitavoloboev** [comment]
@TommyX12 

> Reverting to 1.25.2 solves this issue

How did you do it?

**Comment by dj-blake** [comment]
Same issue. Really frustrating as it drops key presses quite frequently.

Note I don't use co-pilot, so it is not specifically due to interaction with that extension, though it does occur particularly when Intellisense is popping up suggestions.

Downgraded to 1.25.2 as well to avoid the issue.

**Comment by hawkinsw** [comment]
I want to say that I, too, am experiencing this issue. While it *is* frustrating, I completely understand that you are all doing the best that you can to make this incredibly awesome tool for the community and doing it in your free time. Thank you all for the work that you do!

**Comment by nachomglz** [comment]
Please fix this, when you type fast it drops like 30% of the characters, it's really frustrating.

**Comment by darrenchurchill** [comment]
It looks like the issue is from 50bc4fe1e32434cc15098173a5dfc42c7818ac8e.

I'm not familiar with the code at all, but I set up a macro on my keyboard to rapidly output the string `"asdfghjkl asdfghjkl "`, and ran the extension various times during a `git bisect`. After removing the `TaskQueue`, the extension seems capable of losing track of the order keys were pressed in, missing keypresses, and even generating duplicate keypresses.

I hope this is helpful, I attached a couple screencasts of bad and good behavior.

https://github.com/VSCodeVim/Vim/assets/32401097/d2570243-9ae2-45b3-9998-df81e4606046


https://github.com/VSCodeVim/Vim/assets/32401097/90c52aeb-147c-4437-a607-0595384676e2

**Comment by clauderoy790** [comment]
I can attest to this as well. I work on a Macbook Pro 2017 that is getting slow and before 1.26 I never had that problem but with 1.26 not only some characters will be missing, but it will add repeats and will mess up the order of the characters that I typed, it makes the extension completely unusable for me but using 1.25.2 solves everything for me.

**Comment by cTurnerEnvAU** [comment]
I had raised this separately as #8611 but I'm pretty sure this is the same issue so I'm just gonna drop the key details in as a comment.

When in insert mode, keystrokes following dual function keys (eg. https://github.com/qmk/qmk_firmware/blob/master/docs/tap_hold.md) are not being registered. I use an ergodox EZ with home row modifier keys: holding `s`/`l` yields `ctrl`, `d`/`k` `alt` and `f`/`j` the windows/meta key. This leads to typos such as `form` -> `frm`, `site` -> `ste`, etc.

- Unlike other cases of this issue here, this only appeared to occur *directly* after modifier keys. Hopefully this might be useful information to someone with a good understanding of how QMK firmware sends keystrokes.

Rolling back vscodevim to version 1.25.2 resolves the issue.

**Comment by GaurangTandon** [comment]
Can we please at least rollback this version, until the fix is deployed? I have had this issue for close to 2 weeks, and all this while, I thought Create React App is causing VS Code to slow down 😃 There might be many more users with the same idea as me, still stuck on the latest version.

**Comment by Beatusvir** [comment]
I'm also having this issue, reverted to previous as mentioned in here fixes it.

**Comment by dycw** [comment]
I can attest to this. This is extremely frustrating.

**Comment by Testare** [comment]
Is this fix live? I see 1.26.1 in the changelog as being live since 25 September, but there's no git tag and I can't install it.
