### ISSUE TITLE
Cmd+s enters insert mode

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#975]
### Technical details:
- VSCode Version: 1.7 Insider
- VsCodeVim Version: 0.3.8
- OS: OS X 10.11.6

**Comment by rebornix** [comment]
Let me explain a little bit why this happens. `cmd+s` is not changing the mode to `Insert` while it changes the cursor style from `block` to `line`. The reason it happens is `cmd+s` triggers document save, which triggers another view update of VS Code. When the view updates, it will read configuration from `settings.json` as latest Code will persist all changes to Code's configuration through API and it always reads config from the file. Since we are not merging #913 yet, we don't save the change to cursor style to `settings.json`, so Code thinks the cursor style is `line` instead of `block`.

This problem can be solved once #913 is merged.

**Comment by octref** [comment]
@rebornix This doesn't happen anymore. #913 is merged. So I guess this can be closed?

**Comment by rebornix** [comment]
@octref yes, it's covered by that PR, thanks!
