### ISSUE TITLE
Reselect-Visual (gv)

### ISSUE THREAD

**Issue by dw9** [VSCodeVim/Vim#986]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?
1. Enter visual mode and select an area (across one or more lines)
2. Exit visual mode (e.g. by yanking or `ESC`)
3. Type `gv`
### What did you expect to happen?

The editor should enter visual mode with the same area selected as the previous area.
### What happened instead?

Nothing
### Technical details:
- VSCode Version: 1.6.1
- VsCodeVim Version: 0.3.8
- OS: Arch Linux

**Comment by johnfn** [comment]
Where do you guys find all these esoteric Vim features? :-)

Should be an easy one to add.

**Comment by proehlen** [comment]
This would be very helpful to me.  Even more helpful to me would be `gp`:

http://vim.wikia.com/wiki/Selecting_your_pasted_text

This text from the above link is the exact use case that I find wanting to do over and over again:

> For example, you may want to paste some text, then select it for indenting, or formatting, or performing a substitution.

Not logging it as a separate issue/feature request in case it can be implemented at the same time as `gv` since it appears to be somewhat related.

Thanks for your excellent package.
